=== JamesSkemp/media.jamesrskemp/xsd/2010/09/06/ShadowHeartsCovenant.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="details">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="characters">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="notes" minOccurs="0" type="xs:string"/>
							<xs:element name="character" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="level" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger"
												use="required"/>
												<xs:attribute name="hp" type="xs:positiveInteger"
												use="required"/>
												<xs:attribute name="mp" type="xs:nonNegativeInteger"
												use="required"/>
												<xs:attribute name="sp" type="xs:nonNegativeInteger"
												use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/media.jamesrskemp/xml/ShadowHeartsCovenant.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Licensed under the Creative Commons License Attribution-Noncommercial-Share Alike 3.0 (http://creativecommons.org/licenses/by-nc-sa/3.0/). Contact information for attribution at http://jamesrskemp.com/ -->
<!-- Character data and Kurando Fusions based on content written 12/24/2005-1/1/2006. -->
<details xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://media.jamesrskemp.com/xsd/2010/09/06/ShadowHeartsCovenant.xsd">
	<characters>
		<character name="Karin">
			<level id="1" hp="25" mp="15" sp="4"/>
			<level id="2" hp="35" mp="26" sp="4"/>
			<level id="3" hp="46" mp="37" sp="4"/>
			<level id="4" hp="56" mp="48" sp="5"/>
			<level id="5" hp="66" mp="59" sp="5"/>
			<level id="6" hp="76" mp="69" sp="5"/>
			<level id="7" hp="87" mp="80" sp="5"/>
			<level id="8" hp="97" mp="97" sp="6"/>
			<level id="9" hp="107" mp="102" sp="6"/>
			<level id="10" hp="117" mp="113" sp="6"/>
			<level id="11" hp="128" mp="124" sp="6"/>
			<level id="12" hp="138" mp="135" sp="6"/>
			<level id="13" hp="148" mp="146" sp="7"/>
			<level id="14" hp="158" mp="157" sp="7"/>
			<level id="15" hp="169" mp="168" sp="7"/>
			<level id="16" hp="179" mp="178" sp="7"/>
			<level id="17" hp="189" mp="189" sp="7"/>
			<level id="18" hp="199" mp="200" sp="8"/>
			<level id="19" hp="210" mp="211" sp="8"/>
			<level id="20" hp="220" mp="222" sp="8"/>
			<level id="21" hp="233" mp="233" sp="8"/>
			<level id="22" hp="247" mp="243" sp="9"/>
			<level id="23" hp="260" mp="254" sp="9"/>
			<level id="24" hp="273" mp="265" sp="9"/>
			<level id="25" hp="287" mp="276" sp="9"/>
			<level id="26" hp="300" mp="286" sp="9"/>
			<level id="27" hp="314" mp="297" sp="10"/>
			<level id="28" hp="327" mp="308" sp="10"/>
			<level id="29" hp="340" mp="318" sp="10"/>
			<level id="30" hp="354" mp="329" sp="10"/>
			<level id="31" hp="367" mp="340" sp="11"/>
			<level id="32" hp="380" mp="350" sp="11"/>
			<level id="33" hp="394" mp="367" sp="11"/>
			<level id="34" hp="407" mp="372" sp="11"/>
			<level id="35" hp="421" mp="383" sp="11"/>
			<level id="36" hp="434" mp="393" sp="12"/>
			<level id="37" hp="447" mp="404" sp="12"/>
			<level id="38" hp="467" mp="415" sp="12"/>
			<level id="39" hp="474" mp="425" sp="12"/>
			<level id="40" hp="487" mp="436" sp="12"/>
			<level id="41" hp="501" mp="447" sp="13"/>
			<level id="42" hp="514" mp="457" sp="13"/>
			<level id="43" hp="527" mp="468" sp="13"/>
			<level id="44" hp="541" mp="479" sp="13"/>
			<level id="45" hp="554" mp="490" sp="14"/>
			<level id="46" hp="568" mp="500" sp="14"/>
			<level id="47" hp="581" mp="511" sp="14"/>
			<level id="48" hp="594" mp="522" sp="14"/>
			<level id="49" hp="608" mp="532" sp="14"/>
			<level id="50" hp="621" mp="543" sp="15"/>
			<level id="51" hp="631" mp="554" sp="15"/>
			<level id="52" hp="641" mp="564" sp="15"/>
			<level id="53" hp="651" mp="575" sp="15"/>
			<level id="54" hp="661" mp="586" sp="16"/>
			<level id="55" hp="671" mp="597" sp="16"/>
			<level id="56" hp="681" mp="607" sp="16"/>
			<level id="57" hp="691" mp="618" sp="16"/>
			<level id="58" hp="701" mp="629" sp="16"/>
			<level id="59" hp="711" mp="639" sp="17"/>
			<level id="60" hp="722" mp="650" sp="17"/>
			<level id="61" hp="732" mp="661" sp="17"/>
			<level id="62" hp="742" mp="671" sp="17"/>
			<level id="63" hp="752" mp="682" sp="17"/>
			<level id="64" hp="762" mp="693" sp="18"/>
		</character>
		<character name="Yuri">
			<level id="4" hp="58" mp="36" sp="23"/>
			<level id="5" hp="69" mp="44" sp="24"/>
			<level id="6" hp="80" mp="53" sp="25"/>
			<level id="7" hp="97" mp="67" sp="26"/>
			<level id="8" hp="102" mp="70" sp="27"/>
			<level id="9" hp="112" mp="78" sp="28"/>
			<level id="10" hp="123" mp="87" sp="29"/>
			<level id="11" hp="134" mp="95" sp="30"/>
			<level id="12" hp="145" mp="104" sp="31"/>
			<level id="13" hp="155" mp="112" sp="32"/>
			<level id="14" hp="166" mp="121" sp="33"/>
			<level id="15" hp="177" mp="129" sp="34"/>
			<level id="16" hp="188" mp="138" sp="35"/>
			<level id="17" hp="199" mp="146" sp="36"/>
			<level id="18" hp="209" mp="155" sp="37"/>
			<level id="19" hp="220" mp="163" sp="37"/>
			<level id="20" hp="231" mp="172" sp="38"/>
			<level id="21" hp="245" mp="181" sp="39"/>
			<level id="22" hp="259" mp="190" sp="40"/>
			<level id="23" hp="273" mp="199" sp="41"/>
			<level id="24" hp="287" mp="208" sp="42"/>
			<level id="25" hp="301" mp="217" sp="43"/>
			<level id="26" hp="315" mp="226" sp="44"/>
			<level id="27" hp="329" mp="236" sp="45"/>
			<level id="28" hp="343" mp="245" sp="46"/>
			<level id="29" hp="357" mp="254" sp="47"/>
			<level id="30" hp="371" mp="263" sp="48"/>
			<level id="31" hp="385" mp="272" sp="49"/>
			<level id="32" hp="399" mp="281" sp="50"/>
			<level id="33" hp="413" mp="290" sp="51"/>
			<level id="34" hp="427" mp="299" sp="52"/>
			<level id="35" hp="441" mp="308" sp="53"/>
			<level id="36" hp="454" mp="317" sp="54"/>
			<level id="37" hp="468" mp="326" sp="55"/>
			<level id="38" hp="482" mp="335" sp="56"/>
			<level id="39" hp="496" mp="345" sp="57"/>
			<level id="40" hp="510" mp="354" sp="58"/>
			<level id="41" hp="524" mp="363" sp="59"/>
			<level id="42" hp="538" mp="372" sp="60"/>
			<level id="43" hp="552" mp="381" sp="61"/>
			<level id="44" hp="566" mp="390" sp="62"/>
			<level id="45" hp="580" mp="399" sp="63"/>
			<level id="46" hp="594" mp="408" sp="64"/>
			<level id="47" hp="608" mp="417" sp="65"/>
			<level id="48" hp="622" mp="426" sp="66"/>
			<level id="49" hp="636" mp="435" sp="67"/>
			<level id="50" hp="650" mp="444" sp="68"/>
			<level id="51" hp="661" mp="453" sp="69"/>
			<level id="52" hp="671" mp="463" sp="70"/>
			<level id="53" hp="682" mp="472" sp="70"/>
			<level id="54" hp="692" mp="481" sp="71"/>
			<level id="55" hp="703" mp="490" sp="72"/>
			<level id="56" hp="713" mp="499" sp="73"/>
			<level id="57" hp="724" mp="508" sp="74"/>
			<level id="58" hp="734" mp="517" sp="75"/>
			<level id="59" hp="745" mp="526" sp="76"/>
			<level id="60" hp="755" mp="535" sp="77"/>
			<level id="61" hp="766" mp="544" sp="78"/>
			<level id="62" hp="776" mp="553" sp="79"/>
			<level id="63" hp="787" mp="562" sp="80"/>
			<level id="64" hp="797" mp="572" sp="81"/>
		</character>
		<character name="Gepetto">
			<level id="3" hp="38" mp="45" sp="8"/>
			<level id="4" hp="47" mp="58" sp="9"/>
			<level id="5" hp="56" mp="71" sp="9"/>
			<level id="6" hp="65" mp="83" sp="9"/>
			<level id="7" hp="74" mp="96" sp="9"/>
			<level id="8" hp="83" mp="108" sp="10"/>
			<level id="9" hp="92" mp="121" sp="10"/>
			<level id="10" hp="101" mp="134" sp="10"/>
			<level id="11" hp="109" mp="146" sp="10"/>
			<level id="12" hp="118" mp="159" sp="10"/>
			<level id="13" hp="127" mp="172" sp="11"/>
			<level id="14" hp="136" mp="184" sp="11"/>
			<level id="15" hp="145" mp="197" sp="11"/>
			<level id="16" hp="154" mp="209" sp="11"/>
			<level id="17" hp="163" mp="222" sp="11"/>
			<level id="18" hp="172" mp="235" sp="12"/>
			<level id="19" hp="181" mp="247" sp="12"/>
			<level id="20" hp="190" mp="260" sp="12"/>
			<level id="21" hp="202" mp="272" sp="12"/>
			<level id="22" hp="213" mp="285" sp="13"/>
			<level id="23" hp="225" mp="297" sp="13"/>
			<level id="24" hp="236" mp="310" sp="13"/>
			<level id="25" hp="248" mp="322" sp="13"/>
			<level id="26" hp="260" mp="335" sp="13"/>
			<level id="27" hp="271" mp="347" sp="14"/>
			<level id="28" hp="283" mp="360" sp="14"/>
			<level id="29" hp="294" mp="372" sp="14"/>
			<level id="30" hp="306" mp="385" sp="14"/>
			<level id="31" hp="318" mp="397" sp="15"/>
			<level id="32" hp="329" mp="410" sp="15"/>
			<level id="33" hp="341" mp="422" sp="15"/>
			<level id="34" hp="352" mp="435" sp="15"/>
			<level id="35" hp="364" mp="447" sp="15"/>
			<level id="36" hp="376" mp="460" sp="16"/>
			<level id="37" hp="387" mp="472" sp="16"/>
			<level id="38" hp="399" mp="485" sp="16"/>
			<level id="39" hp="410" mp="497" sp="16"/>
			<level id="40" hp="422" mp="510" sp="16"/>
			<level id="41" hp="434" mp="522" sp="17"/>
			<level id="42" hp="445" mp="535" sp="17"/>
			<level id="43" hp="457" mp="547" sp="17"/>
			<level id="44" hp="468" mp="560" sp="17"/>
			<level id="45" hp="480" mp="572" sp="18"/>
			<level id="46" hp="492" mp="584" sp="18"/>
			<level id="47" hp="503" mp="597" sp="18"/>
			<level id="48" hp="515" mp="609" sp="18"/>
			<level id="49" hp="526" mp="622" sp="18"/>
			<level id="50" hp="538" mp="634" sp="19"/>
			<level id="51" hp="547" mp="647" sp="19"/>
			<level id="52" hp="555" mp="659" sp="19"/>
			<level id="53" hp="564" mp="672" sp="19"/>
			<level id="54" hp="572" mp="684" sp="20"/>
		</character>
		<character name="Blanca">
			<level id="3" hp="44" mp="35" sp="7"/>
			<level id="4" hp="54" mp="45" sp="8"/>
			<level id="5" hp="65" mp="55" sp="8"/>
			<level id="6" hp="75" mp="66" sp="8"/>
			<level id="7" hp="85" mp="76" sp="8"/>
			<level id="8" hp="95" mp="87" sp="9"/>
			<level id="9" hp="105" mp="97" sp="9"/>
			<level id="10" hp="115" mp="107" sp="9"/>
			<level id="11" hp="126" mp="118" sp="9"/>
			<level id="12" hp="136" mp="128" sp="9"/>
			<level id="13" hp="146" mp="138" sp="10"/>
			<level id="14" hp="156" mp="149" sp="10"/>
			<level id="15" hp="166" mp="159" sp="10"/>
			<level id="16" hp="176" mp="170" sp="10"/>
			<level id="17" hp="187" mp="180" sp="10"/>
			<level id="18" hp="197" mp="190" sp="11"/>
			<level id="19" hp="207" mp="201" sp="11"/>
			<level id="20" hp="217" mp="211" sp="11"/>
			<level id="21" hp="230" mp="221" sp="11"/>
			<level id="22" hp="243" mp="231" sp="12"/>
			<level id="23" hp="257" mp="241" sp="12"/>
			<level id="24" hp="270" mp="252" sp="12"/>
			<level id="25" hp="283" mp="262" sp="12"/>
			<level id="26" hp="296" mp="272" sp="12"/>
			<level id="27" hp="309" mp="282" sp="13"/>
			<level id="28" hp="323" mp="292" sp="13"/>
			<level id="29" hp="336" mp="302" sp="13"/>
			<level id="30" hp="349" mp="313" sp="13"/>
