=== JamesSkemp/media.jamesrskemp/xsd/2010/09/03/OnimushaDawnOfDreams.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="onimushaDawnOfDreams">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="armor">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="level">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
									<xs:attribute name="souls" type="xs:nonNegativeInteger"
										use="required">
										<xs:annotation><xs:documentation>Number of souls to reach the next level.</xs:documentation></xs:annotation>
									</xs:attribute>
									<xs:attribute name="slots" type="xs:positiveInteger"
										use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/media.jamesrskemp/xml/OnimushaDawnOfDreams.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Licensed under the Creative Commons License Attribution-Noncommercial-Share Alike 3.0 (http://creativecommons.org/licenses/by-nc-sa/3.0/). Contact information for attribution at http://jamesrskemp.com/ -->
<!-- Armor data based on content written 5/11-4/2006. -->
<onimushaDawnOfDreams xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://media.jamesrskemp.com/xsd/2010/09/03/OnimushaDawnOfDreams.xsd">
	<armor>
		<level id="1" souls="100" slots="1"/>
		<level id="2" souls="110" slots="1"/>
		<level id="3" souls="120" slots="1"/>
		<level id="4" souls="130" slots="1"/>
		<level id="5" souls="140" slots="1"/>
		<level id="6" souls="150" slots="1"/>
		<level id="7" souls="160" slots="1"/>
		<level id="8" souls="170" slots="1"/>
		<level id="9" souls="180" slots="1"/>
		<level id="10" souls="190" slots="2"/>
		<level id="11" souls="200" slots="2"/>
		<level id="12" souls="210" slots="2"/>
		<level id="13" souls="220" slots="2"/>
		<level id="14" souls="230" slots="2"/>
		<level id="15" souls="240" slots="2"/>
		<level id="16" souls="250" slots="2"/>
		<level id="17" souls="260" slots="2"/>
		<level id="18" souls="270" slots="2"/>
		<level id="19" souls="280" slots="2"/>
		<level id="20" souls="290" slots="3"/>
		<level id="21" souls="300" slots="3"/>
		<level id="22" souls="310" slots="3"/>
		<level id="23" souls="320" slots="3"/>
		<level id="24" souls="330" slots="3"/>
		<level id="25" souls="340" slots="3"/>
		<level id="26" souls="350" slots="3"/>
		<level id="27" souls="360" slots="3"/>
		<level id="28" souls="370" slots="3"/>
		<level id="29" souls="380" slots="3"/>
		<level id="30" souls="390" slots="4"/>
		<level id="31" souls="400" slots="4"/>
		<level id="32" souls="410" slots="4"/>
		<level id="33" souls="420" slots="4"/>
		<level id="34" souls="430" slots="4"/>
		<level id="35" souls="440" slots="4"/>
		<level id="36" souls="450" slots="4"/>
		<level id="37" souls="460" slots="4"/>
		<level id="38" souls="470" slots="4"/>
		<level id="39" souls="480" slots="4"/>
		<level id="40" souls="490" slots="4"/>
		<level id="41" souls="500" slots="4"/>
		<level id="42" souls="520" slots="4"/>
		<level id="43" souls="540" slots="4"/>
		<level id="44" souls="560" slots="4"/>
		<level id="45" souls="580" slots="4"/>
		<level id="46" souls="600" slots="4"/>
		<level id="47" souls="620" slots="4"/>
		<level id="48" souls="640" slots="4"/>
		<level id="49" souls="660" slots="4"/>
		<level id="50" souls="680" slots="4"/>
		<level id="51" souls="700" slots="4"/>
		<level id="52" souls="720" slots="4"/>
		<level id="53" souls="740" slots="4"/>
		<level id="54" souls="760" slots="4"/>
		<level id="55" souls="780" slots="4"/>
		<level id="56" souls="800" slots="4"/>
		<level id="57" souls="820" slots="4"/>
		<level id="58" souls="840" slots="4"/>
		<level id="59" souls="860" slots="4"/>
		<level id="60" souls="880" slots="4"/>
		<level id="61" souls="900" slots="4"/>
		<level id="62" souls="920" slots="4"/>
		<level id="63" souls="940" slots="4"/>
		<level id="64" souls="960" slots="4"/>
		<level id="65" souls="980" slots="4"/>
		<level id="66" souls="1000" slots="4"/>
		<level id="67" souls="1050" slots="4"/>
		<level id="68" souls="1100" slots="4"/>
		<level id="69" souls="1150" slots="4"/>
		<level id="70" souls="1200" slots="4"/>
		<level id="71" souls="1250" slots="4"/>
		<level id="72" souls="1300" slots="4"/>
		<level id="73" souls="1350" slots="4"/>
		<level id="74" souls="1400" slots="4"/>
		<level id="75" souls="1450" slots="4"/>
		<level id="76" souls="1500" slots="4"/>
		<level id="77" souls="1550" slots="4"/>
		<level id="78" souls="1600" slots="4"/>
		<level id="79" souls="1650" slots="4"/>
		<level id="80" souls="1700" slots="4"/>
		<level id="81" souls="1750" slots="4"/>
		<level id="82" souls="1800" slots="4"/>
		<level id="83" souls="1850" slots="4"/>
		<level id="84" souls="1900" slots="4"/>
		<level id="85" souls="1950" slots="4"/>
		<level id="86" souls="2000" slots="4"/>
		<level id="87" souls="2050" slots="4"/>
		<level id="88" souls="2100" slots="4"/>
		<level id="89" souls="2150" slots="4"/>
		<level id="90" souls="2200" slots="4"/>
		<level id="91" souls="2250" slots="4"/>
		<level id="92" souls="2300" slots="4"/>
		<level id="93" souls="2350" slots="4"/>
		<level id="94" souls="2400" slots="4"/>
		<level id="95" souls="2450" slots="4"/>
		<level id="96" souls="2500" slots="4"/>
		<level id="97" souls="2550" slots="4"/>
		<level id="98" souls="2600" slots="4"/>
		<level id="99" souls="2650" slots="4"/>
		<level id="100" souls="0" slots="4"/>
	</armor>
</onimushaDawnOfDreams>
