=== JamesSkemp/media.jamesrskemp/xsd/2010/11/16/CrisisCoreFinalFantasy7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="missions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="categories">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="10" name="category">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="1" name="subcategories">
											<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="6" name="subcategory">
												<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger"
												use="required"/>
												<xs:attribute name="name" use="required"/>
												</xs:complexType>
												</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
									<xs:attribute name="name" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="mission" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name"/>
							<xs:element name="location"/>
							<xs:element name="enemies" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="enemy"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="bosses">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="boss">
											<xs:complexType>
												<xs:simpleContent>
												<xs:extension base="xs:string">
												<xs:attribute name="quantity"
												type="xs:positiveInteger"/>
												</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="chests" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="chest" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
												<xs:extension base="xs:string">
												<xs:attribute name="quantity"
												type="xs:positiveInteger"/>
												</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="rewards">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="reward">
											<xs:complexType>
												<xs:simpleContent>
												<xs:extension base="xs:string">
												<xs:attribute name="quantity"
												type="xs:positiveInteger"/>
												</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="requirements">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="requirement">
											<xs:complexType>
												<xs:simpleContent>
												<xs:extension base="xs:string">
												<xs:attribute name="chapter" type="xs:boolean"/>
												<xs:attribute name="mission" type="xs:boolean"/>
												</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required"/>
						<xs:attribute name="category" type="xs:positiveInteger" use="required"/>
						<xs:attribute name="subcategory" type="xs:positiveInteger" use="required"/>
						<xs:attribute name="order" type="xs:positiveInteger" use="required"/>
						<xs:attribute name="missable" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/media.jamesrskemp/xml/CrisisCoreFinalFantasy7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Licensed under the Creative Commons License Attribution-Noncommercial-Share Alike 3.0 (http://creativecommons.org/licenses/by-nc-sa/3.0/). Contact information for attribution at http://jamesrskemp.com/ -->
<missions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://media.jamesrskemp.com/xsd/2010/11/16/CrisisCoreFinalFantasy7.xsd">
	<categories>
		<category id="1" name="Shinra Electric Company">
			<subcategories>
				<subcategory id="1" name="Training Missions"/>
				<subcategory id="2" name="Peacekeeping Troops"/>
				<subcategory id="3" name="Weapons Development"/>
				<subcategory id="4" name="Plan for New Equipment"/>
				<subcategory id="5" name="Special Operations Arm Laboratory"/>
			</subcategories>
		</category>
		<category id="2" name="Monster Research Project">
			<subcategories>
				<subcategory id="1" name="Monsters in Midgar"/>
				<subcategory id="2" name="Monster Reports"/>
				<subcategory id="3" name="Monster Incidents"/>
				<subcategory id="4" name="Unexplored Territories"/>
				<subcategory id="5" name="In Search of the Unknown"/>
			</subcategories>
		</category>
		<category id="3" name="Genesis's Forces">
			<subcategories>
				<subcategory id="1" name="Genesis's Forces on the March"/>
				<subcategory id="2" name="Major Offensives"/>
				<subcategory id="3" name="Clash with Genesis's Forces"/>
				<subcategory id="4" name="Genesis Evolution"/>
				<subcategory id="5" name="The Strongest Copies"/>
			</subcategories>
		</category>
		<category id="4" name="To End the War with Wutai">
			<subcategories>
				<subcategory id="1" name="Pursue the Remnants"/>
				<subcategory id="2" name="Behind the Scenes"/>
				<subcategory id="3" name="The Crescent Unit"/>
				<subcategory id="4" name="The Remnants Strike Again"/>
				<subcategory id="5" name="Annihilate the Crescent Unit"/>
			</subcategories>
		</category>
		<category id="5" name="Hojo's Laboratory">
			<subcategories>
				<subcategory id="1" name="Sample Monsters Lv. 1"/>
				<subcategory id="2" name="Sample Monsters Lv. 2"/>
				<subcategory id="3" name="Sample Monsters Lv. 3"/>
				<subcategory id="4" name="Sample Monsters Lv. 4"/>
			</subcategories>
		</category>
		<category id="6" name="Seeking Precious Items">
			<subcategories>
				<subcategory id="1" name="Looking for Items"/>
				<subcategory id="2" name="Midgar City Development Department"/>
				<subcategory id="3" name="Zack, The Treasure Hunter"/>
				<subcategory id="4" name="Zack, the Clean-Up Guy"/>
				<subcategory id="5" name="Zack, the Corporation Crusher"/>
				<subcategory id="6" name="Counter-Mafia Project"/>
			</subcategories>
		</category>
		<category id="7" name="Seeking Priceless Items">
			<subcategories>
				<subcategory id="1" name="Recall Missions"/>
				<subcategory id="2" name="Precious Things"/>
				<subcategory id="3" name="ESP Development Project"/>
				<subcategory id="4" name="Contacts From P"/>
				<subcategory id="5" name="Orphans Escaping"/>
				<subcategory id="6" name="The Accessory Craftsman"/>
			</subcategories>
		</category>
		<category id="8" name="Zack, the Materia Hunter">
			<subcategories>
				<subcategory id="1" name="Starting Out"/>
				<subcategory id="2" name="Mako Stones"/>
				<subcategory id="3" name="To Hell and Back"/>
				<subcategory id="4" name="From a Hot Treasure Hunter"/>
				<subcategory id="5" name="Anonymous Hints"/>
				<subcategory id="6" name="Yuffie's Notices"/>
			</subcategories>
		</category>
		<category id="9" name="Great Caves of Wonders">
			<subcategories>
				<subcategory id="1" name="Invitations to the Underground"/>
				<subcategory id="2" name="Stirrings"/>
				<subcategory id="3" name="In Search of What?"/>
				<subcategory id="4" name="Realm of Demons"/>
				<subcategory id="5" name="Unknown Energy"/>
				<subcategory id="6" name="Doors to the Unknown"/>
			</subcategories>
		</category>
		<category id="10" name="Mysteries of the World">
			<subcategories>
				<subcategory id="1" name="Cactoid Secrets"/>
				<subcategory id="2" name="Tonberry Quests"/>
				<subcategory id="3" name="Fun in the Sun!"/>
				<subcategory id="4" name="More Fun in the Sun"/>
			</subcategories>
		</category>
	</categories>
	<mission id="1-1-1" category="1" subcategory="1" order="1">
		<name>Shinra's Basic Training</name>
		<location/>
		<bosses>
			<boss quantity="8">Sentry</boss>
		</bosses>
		<rewards>
			<reward>Elixir</reward>
		</rewards>
		<requirements>
			<requirement chapter="true">Chapter 2</requirement>
		</requirements>
	</mission>
	<mission id="1-1-2" category="1" subcategory="1" order="2">
		<name>Shinra's Advanced Training</name>
		<location/>
		<bosses>
			<boss quantity="2">Gun Bull Head</boss>
			<boss>Alert Head</boss>
			<boss quantity="2">Grenade Combatant</boss>
			<boss>Captain</boss>
		</bosses>
		<rewards>
			<reward>Hero Drink</reward>
		</rewards>
		<requirements>
			<requirement chapter="true">Chapter 10</requirement>
		</requirements>
	</mission>
	<mission id="1-1-3" category="1" subcategory="1" order="3">
		<name>50 Shinra Troops</name>
		<location/>
		<bosses>
			<boss quantity="45">Chief Petty Officer</boss>
			<boss quantity="5">Sergeant</boss>
		</bosses>
		<rewards>
			<reward quantity="2">Hero Drink</reward>
		</rewards>
		<requirements>
			<requirement mission="true">1-1-2</requirement>
		</requirements>
	</mission>
	<mission id="1-1-4" category="1" subcategory="1" order="4">
		<name>100 Shinra Troops</name>
		<location/>
		<bosses>
			<boss quantity="90">Special Ops Officer</boss>
			<boss quantity="10">Sergeant Major</boss>
		</bosses>
		<rewards>
			<reward>Black Belt</reward>
		</rewards>
		<requirements>
			<requirement mission="true">1-1-3</requirement>
		</requirements>
	</mission>
	<mission id="1-1-5" category="1" subcategory="1" order="5">
		<name>200 Shinra Troops</name>
		<location/>
		<bosses>
			<boss quantity="180">Combatant</boss>
			<boss quantity="20">Warrant Officer</boss>
		</bosses>
		<rewards>
			<reward/>
		</rewards>
		<requirements>
			<requirement mission="true">1-1-4</requirement>
		</requirements>
	</mission>
	<mission id="1-1-6" category="1" subcategory="1" order="6">
		<name/>
		<location/>
		<bosses>
			<boss quantity="900">Guard</boss>
			<boss quantity="100">Ensign</boss>
		</bosses>
		<rewards>
			<reward>Mug materia</reward>
		</rewards>
		<requirements>
			<requirement mission="true">1-1-5</requirement>
		</requirements>
	</mission>
	<mission id="1-2-1" category="1" subcategory="2" order="1" missable="true">
		<name>Challenge from Security</name>
		<location/>
		<enemies>
			<enemy/>
		</enemies>
		<bosses>
			<boss quantity="2">Storm Trooper</boss>
			<boss quantity="2">Corporal</boss>
		</bosses>
		<chests>
			<chest>Remedy</chest>
			<chest>X-Potion</chest>
		</chests>
		<rewards>
			<reward>Shinra Alpha</reward>
		</rewards>
		<requirements>
			<requirement chapter="true">Chapter 3</requirement>
			<requirement>Speak with Shinra Captain in Loveless Street.</requirement>
		</requirements>
	</mission>
	<mission id="1-2-2" category="1" subcategory="2" order="2">
		<name>Second Challenge</name>
		<location/>
		<enemies>
			<enemy/>
		</enemies>
		<bosses>
			<boss>Corporal</boss>
			<boss quantity="3">Red Saucer I</boss>
		</bosses>
		<chests>
			<chest>X-Potion</chest>
		</chests>
		<rewards>
			<reward>Silence materia</reward>
		</rewards>
		<requirements>
			<requirement mission="true">1-2-1</requirement>
		</requirements>
	</mission>
	<mission id="1-2-3" category="1" subcategory="2" order="3">
		<name>Third Challenge</name>
		<location/>
		<enemies>
			<enemy/>
		</enemies>
		<bosses>
			<boss quantity="2">Corporal</boss>
			<boss quantity="2">Red Saucer I</boss>
		</bosses>
		<chests>
			<chest>Hi-Potion</chest>
			<chest>Elixir</chest>
		</chests>
		<rewards>
			<reward>Four Slots</reward>
		</rewards>
		<requirements>
			<requirement mission="true">1-2-2</requirement>
		</requirements>
	</mission>
	<mission id="1-2-4" category="1" subcategory="2" order="4">
		<name>Getting Serious</name>
		<location/>
		<enemies>
			<enemy/>
		</enemies>
		<bosses>
			<boss quantity="4">Corporal</boss>
		</bosses>
		<chests>
			<chest>Soma</chest>
			<chest>Hi-Potion</chest>
		</chests>
		<rewards>
			<reward>Force Bracelet</reward>
		</rewards>
		<requirements>
			<requirement mission="true">1-2-3</requirement>
		</requirements>
	</mission>
	<mission id="1-2-5" category="1" subcategory="2" order="5">
		<name>Armed Challenge</name>
		<location/>
		<enemies>
			<enemy/>
		</enemies>
		<bosses>
			<boss quantity="2">Sweeper+</boss>
		</bosses>
		<chests>
			<chest>Potion</chest>
			<chest>Hi-Potion</chest>
			<chest>Remedy</chest>
		</chests>
		<rewards>
			<reward>Ice Armlet</reward>
		</rewards>
		<requirements>
			<requirement mission="true">1-2-4</requirement>
		</requirements>
	</mission>
	<mission id="1-2-6" category="1" subcategory="2" order="6">
		<name>Last Challenge</name>
		<location/>
		<enemies>
			<enemy/>
		</enemies>
		<bosses>
			<boss>Arachno</boss>
		</bosses>
		<chests>
			<chest>Elixir</chest>
			<chest>Soma</chest>
		</chests>
		<rewards>
			<reward>Fat Chocobo Feather</reward>
		</rewards>
		<requirements>
			<requirement mission="true">1-2-6</requirement>
		</requirements>
	</mission>
	<mission id="1-3-1" category="1" subcategory="3" order="1">
		<name>Next-Generation Weapons</name>
		<location/>
		<enemies>
			<enemy/>
		</enemies>
		<bosses>
			<boss/>
		</bosses>
		<rewards>
			<reward/>
		</rewards>
		<requirements>
			<requirement chapter="true">Chapter 6</requirement>
		</requirements>
	</mission>
	<mission id="1-3-2" category="1" subcategory="3" order="2">
		<name>New Mechanical Weapons</name>
		<location/>
		<enemies>
			<enemy/>
		</enemies>
		<bosses>
			<boss/>
		</bosses>
		<chests>
			<chest/>
		</chests>
		<rewards>
			<reward/>
		</rewards>
		<requirements>
			<requirement mission="true">1-3-1</requirement>
		</requirements>
	</mission>
