=== JamesSkemp/media.jamesrskemp/dtd/vehicle_gas.dtd
<!ELEMENT vehicles (personNameFirst, personNameLast, vehicle*)>

<!ELEMENT personNameFirst (#PCDATA)>
<!ELEMENT personNameLast (#PCDATA)>

<!ELEMENT vehicle (make, model, year, fillups)>
<!ATTLIST vehicle id CDATA #REQUIRED>

<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!ELEMENT fillups (fillup*)>

<!ELEMENT fillup (date, milesCar, milesDriven, gallons, costGallon, costTotal, notes)>
<!ATTLIST fillup
	id CDATA #REQUIRED
	partial (true|false) "false">

<!ELEMENT date (#PCDATA)>
<!ELEMENT milesCar (#PCDATA)>
<!ELEMENT milesDriven (#PCDATA)>
<!ELEMENT gallons (#PCDATA)>
<!ELEMENT costGallon (#PCDATA)>
<!ELEMENT costTotal (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

=== JamesSkemp/media.jamesrskemp/xml/vehicle_gas.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE vehicles SYSTEM "http://media.jamesrskemp.com/dtd/vehicle_gas.dtd">
<!--<?xml-stylesheet type="text/css" href="http://media.jamesrskemp.com/xslt/vehicle_gas.css"?>-->
<?xml-stylesheet type="text/xsl" href="../xslt/vehicle_gas.xslt"?>
<!--<vehicles xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://media.jamesrskemp.net/xsd/vehicle_gas.xsd">-->
<vehicles>
	<personNameFirst>James</personNameFirst>
	<personNameLast>Skemp</personNameLast>
	<vehicle id="1">
		<make>VW</make>
		<model>Golf</model>
		<year>1987</year>
		<fillups>
			<fillup id="1">
				<date>2005-06-27</date>
				<milesCar>149210</milesCar>
				<milesDriven>0</milesDriven>
				<gallons>7.701</gallons>
				<costGallon>2.259</costGallon>
				<costTotal>17.40</costTotal>
				<notes/>
			</fillup>
			<fillup id="2">
				<date>2005-07-05</date>
				<milesCar>149391</milesCar>
				<milesDriven>180.9</milesDriven>
				<gallons>6.026</gallons>
				<costGallon>2.259</costGallon>
				<costTotal>13.61</costTotal>
				<notes/>
			</fillup>
			<fillup id="3">
				<date>2005-07-12</date>
				<milesCar>149555</milesCar>
				<milesDriven>164.6</milesDriven>
				<gallons>5.110</gallons>
				<costGallon>2.379</costGallon>
				<costTotal>12.16</costTotal>
				<notes/>
			</fillup>
			<fillup id="4">
				<date>2005-07-20</date>
				<milesCar>149782</milesCar>
				<milesDriven>227.1</milesDriven>
				<gallons>4.294</gallons>
				<costGallon>2.329</costGallon>
				<costTotal>10.00</costTotal>
				<notes>Didn't fill tank</notes>
			</fillup>
			<fillup id="5">
				<date>2005-07-25</date>
				<milesCar>149894</milesCar>
				<milesDriven>111.3</milesDriven>
				<gallons>6.091</gallons>
				<costGallon>2.339</costGallon>
				<costTotal>14.25</costTotal>
				<notes>Finished off tank</notes>
			</fillup>
			<fillup id="6">
				<date>2005-07-29</date>
				<milesCar>150087</milesCar>
				<milesDriven>193.2</milesDriven>
				<gallons>6.010</gallons>
				<costGallon>2.299</costGallon>
				<costTotal>13.82</costTotal>
				<notes/>
			</fillup>
			<fillup id="7">
				<date>2005-08-02</date>
				<milesCar>150209</milesCar>
				<milesDriven>121.4</milesDriven>
				<gallons>4.028</gallons>
				<costGallon>2.299</costGallon>
				<costTotal>9.26</costTotal>
				<notes/>
			</fillup>
			<fillup id="8">
				<date>2005-08-09</date>
				<milesCar>150412</milesCar>
				<milesDriven>202.5</milesDriven>
				<gallons>6.335</gallons>
				<costGallon>2.399</costGallon>
				<costTotal>15.20</costTotal>
				<notes/>
			</fillup>
			<fillup id="9">
				<date>2005-08-17</date>
				<milesCar>150580</milesCar>
				<milesDriven>167.9</milesDriven>
				<gallons>5.389</gallons>
				<costGallon>2.599</costGallon>
				<costTotal>14.01</costTotal>
				<notes/>
			</fillup>
			<fillup id="10">
				<date>2005-08-27</date>
				<milesCar>150789</milesCar>
				<milesDriven>209.3</milesDriven>
				<gallons>6.320</gallons>
				<costGallon>2.669</costGallon>
				<costTotal>16.87</costTotal>
				<notes/>
			</fillup>
			<fillup id="11">
				<date>2005-09-02</date>
				<milesCar>150906</milesCar>
				<milesDriven>117.0</milesDriven>
				<gallons>3.704</gallons>
				<costGallon>3.199</costGallon>
				<costTotal>11.85</costTotal>
				<notes/>
			</fillup>
			<fillup id="12">
				<date>2005-09-09</date>
				<milesCar>151050</milesCar>
				<milesDriven>143.9</milesDriven>
				<gallons>4.538</gallons>
				<costGallon>2.999</costGallon>
				<costTotal>13.61</costTotal>
				<notes/>
			</fillup>
			<fillup id="13">
				<date>2005-09-15</date>
				<milesCar>151198</milesCar>
				<milesDriven>148.1</milesDriven>
				<gallons>4.447</gallons>
				<costGallon>2.799</costGallon>
				<costTotal>12.45</costTotal>
				<notes/>
			</fillup>
			<fillup id="14">
				<date>2005-09-17</date>
				<milesCar>151247</milesCar>
				<milesDriven>48.7</milesDriven>
				<gallons>1.723</gallons>
				<costGallon>2.759</costGallon>
				<costTotal>4.75</costTotal>
				<notes/>
			</fillup>
			<fillup id="15">
				<date>2005-09-23</date>
				<milesCar>151423</milesCar>
				<milesDriven>175.8</milesDriven>
				<gallons>5.241</gallons>
				<costGallon>2.759</costGallon>
				<costTotal>14.46</costTotal>
				<notes/>
			</fillup>
			<fillup id="16">
				<date>2005-10-02</date>
				<milesCar>151603</milesCar>
				<milesDriven>180.1</milesDriven>
				<gallons>5.639</gallons>
				<costGallon>2.999</costGallon>
				<costTotal>16.91</costTotal>
				<notes/>
			</fillup>
			<fillup id="17">
				<date>2005-10-02</date>
				<milesCar>151701</milesCar>
				<milesDriven>97.5</milesDriven>
				<gallons>2.739</gallons>
				<costGallon>2.929</costGallon>
				<costTotal>8.02</costTotal>
				<notes>Changed spark plugs, fluids, etcetera.</notes>
			</fillup>
			<fillup id="18">
				<date>2005-10-05</date>
				<milesCar>151845</milesCar>
				<milesDriven>144.4</milesDriven>
				<gallons>4.700</gallons>
				<costGallon>2.999</costGallon>
				<costTotal>14.10</costTotal>
				<notes/>
			</fillup>
			<fillup id="19">
				<date>2005-10-14</date>
				<milesCar>152018</milesCar>
				<milesDriven>173.4</milesDriven>
				<gallons>5.666</gallons>
				<costGallon>2.659</costGallon>
				<costTotal>15.07</costTotal>
				<notes/>
			</fillup>
			<fillup id="20">
				<date>2005-10-24</date>
				<milesCar>152217</milesCar>
				<milesDriven>198.8</milesDriven>
				<gallons>7.187</gallons>
				<costGallon>2.559</costGallon>
				<costTotal>18.39</costTotal>
				<notes/>
			</fillup>
			<fillup id="21">
				<date>2005-11-01</date>
				<milesCar>152369</milesCar>
				<milesDriven>151.9</milesDriven>
				<gallons>5.165</gallons>
				<costGallon>2.449</costGallon>
				<costTotal>12.65</costTotal>
				<notes/>
			</fillup>
			<fillup id="22">
				<date>2005-11-10</date>
				<milesCar>152556</milesCar>
				<milesDriven>187.0</milesDriven>
				<gallons>6.330</gallons>
				<costGallon>2.259</costGallon>
				<costTotal>14.30</costTotal>
				<notes/>
			</fillup>
			<fillup id="23">
				<date>2005-11-19</date>
				<milesCar>152762</milesCar>
				<milesDriven>206.0</milesDriven>
				<gallons>7.763</gallons>
				<costGallon>2.229</costGallon>
				<costTotal>17.30</costTotal>
				<notes/>
			</fillup>
			<fillup id="24">
				<date>2005-11-28</date>
				<milesCar>152959</milesCar>
				<milesDriven>196.8</milesDriven>
				<gallons>6.628</gallons>
				<costGallon>2.199</costGallon>
				<costTotal>14.57</costTotal>
				<notes/>
			</fillup>
			<fillup id="25">
				<date>2005-12-05</date>
				<milesCar>153109</milesCar>
				<milesDriven>210.4</milesDriven>
				<gallons>8.160</gallons>
				<costGallon>2.179</costGallon>
				<costTotal>17.78</costTotal>
				<notes>Car is sitting and warming up a lot more now.</notes>
			</fillup>
			<fillup id="26">
				<date>2005-12-13</date>
				<milesCar>153342</milesCar>
				<milesDriven>172.3</milesDriven>
				<gallons>6.911</gallons>
				<costGallon>2.199</costGallon>
				<costTotal>15.20</costTotal>
				<notes/>
			</fillup>
			<fillup id="27">
				<date>2005-12-21</date>
				<milesCar>153488</milesCar>
				<milesDriven>146.0</milesDriven>
				<gallons>6.000</gallons>
				<costGallon>2.259</costGallon>
				<costTotal>13.55</costTotal>
				<notes/>
			</fillup>
			<fillup id="28">
				<date>2005-12-29</date>
				<milesCar>153653</milesCar>
				<milesDriven>165.6</milesDriven>
				<gallons>5.580</gallons>
				<costGallon>2.259</costGallon>
				<costTotal>12.61</costTotal>
				<notes/>
			</fillup>
			<fillup id="29">
				<date>2006-01-06</date>
				<milesCar>153818</milesCar>
				<milesDriven>161.1</milesDriven>
				<gallons>5.930</gallons>
				<costGallon>2.399</costGallon>
				<costTotal>14.22</costTotal>
				<notes>-3.3 from mileage. This is f!ked up - gallons may be off.</notes>
			</fillup>
			<fillup id="30">
				<date>2006-01-12</date>
				<milesCar>153973</milesCar>
				<milesDriven>155.6</milesDriven>
				<gallons>5.433</gallons>
				<costGallon>2.399</costGallon>
				<costTotal>13.03</costTotal>
				<notes/>
			</fillup>
			<fillup id="31">
				<date>2006-01-17</date>
				<milesCar>154121</milesCar>
				<milesDriven>148.2</milesDriven>
				<gallons>5.168</gallons>
				<costGallon>2.359</costGallon>
				<costTotal>12.19</costTotal>
				<notes/>
			</fillup>
			<fillup id="32">
				<date>2006-01-25</date>
				<milesCar>154287</milesCar>
				<milesDriven>165.7</milesDriven>
				<gallons>6.201</gallons>
				<costGallon>2.359</costGallon>
				<costTotal>14.63</costTotal>
				<notes/>
			</fillup>
			<fillup id="33">
				<date>2006-01-31</date>
				<milesCar>154483</milesCar>
				<milesDriven>196.4</milesDriven>
				<gallons>6.583</gallons>
				<costGallon>2.339</costGallon>
				<costTotal>15.40</costTotal>
				<notes/>
			</fillup>
			<fillup id="34">
				<date>2006-02-07</date>
				<milesCar>154633</milesCar>
				<milesDriven>149.9</milesDriven>
				<gallons>5.661</gallons>
				<costGallon>2.399</costGallon>
				<costTotal>13.58</costTotal>
				<notes/>
			</fillup>
			<fillup id="35">
				<date>2006-02-14</date>
				<milesCar>154778</milesCar>
				<milesDriven>144.2</milesDriven>
				<gallons>5.342</gallons>
				<costGallon>2.329</costGallon>
				<costTotal>12.44</costTotal>
				<notes/>
			</fillup>
			<fillup id="36">
				<date>2006-02-22</date>
				<milesCar>154921</milesCar>
				<milesDriven>143.6</milesDriven>
				<gallons>5.551</gallons>
				<costGallon>2.299</costGallon>
				<costTotal>12.76</costTotal>
				<notes/>
			</fillup>
			<fillup id="37">
				<date>2006-03-03</date>
				<milesCar>155105</milesCar>
				<milesDriven>183.3</milesDriven>
				<gallons>6.887</gallons>
				<costGallon>2.399</costGallon>
				<costTotal>16.52</costTotal>
				<notes/>
			</fillup>
			<fillup id="38">
				<date>2006-03-13</date>
				<milesCar>155270</milesCar>
				<milesDriven>165.0</milesDriven>
				<gallons>5.931</gallons>
				<costGallon>2.459</costGallon>
				<costTotal>14.58</costTotal>
				<notes>Got an oil change on the 9th.</notes>
			</fillup>
			<fillup id="39">
