=== JamesSkemp/media.jamesrskemp/xsd/dq8_levels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>
			This schema is used to validate the Dragon Quest VIII levels XML file, stored primarily at http://jamesrskemp.net/ .
		</xs:documentation>
	</xs:annotation>
	<xs:element name="characters" type="charactersType" />

	<xs:complexType name="charactersType">
		<xs:sequence>
			<xs:element name="character" maxOccurs="unbounded">
				<xs:complexType>
					<xs:group ref="characterType" />
					<xs:attribute name="name" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:group name="characterType">
		<xs:sequence>
			<xs:element name="levels" type="levelsType" />
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="levelsType">
		<xs:sequence>
			<xs:element name="level" maxOccurs="unbounded">
				<xs:complexType>
					<xs:group ref="levelType" />
					<xs:attribute name="id" type="xs:integer" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:group name="levelType">
		<xs:sequence>
			<xs:element name="strength" type="xs:nonNegativeInteger" />
			<xs:element name="agility" type="xs:nonNegativeInteger" />
			<xs:element name="resilience" type="xs:nonNegativeInteger" />
			<xs:element name="wisdom" type="xs:nonNegativeInteger" />
			<xs:element name="hitpoints" type="xs:nonNegativeInteger" />
			<xs:element name="magicpoints" type="xs:nonNegativeInteger" />
			<xs:element name="skillpoints" type="xs:nonNegativeInteger" />
			<xs:element name="experience" type="xs:nonNegativeInteger" />
			<xs:element name="spell" type="xs:string" />
		</xs:sequence>
	</xs:group>
</xs:schema>

=== JamesSkemp/media.jamesrskemp/xml/dq8_levels.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xslt/dq8_levels.xsl"?>
<characters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://media.jamesrskemp.com/xsd/dq8_levels.xsd">
	<character name="Hero">
		<levels>
			<level id="1">
				<strength>8</strength>
				<agility>6</agility>
				<resilience>6</resilience>
				<wisdom>5</wisdom>
				<hitpoints>22</hitpoints>
				<magicpoints>0</magicpoints>
				<skillpoints>0</skillpoints>
				<experience>0</experience>
				<spell/>
			</level>
			<level id="2">
				<strength>9</strength>
				<agility>7</agility>
				<resilience>6</resilience>
				<wisdom>6</wisdom>
				<hitpoints>25</hitpoints>
				<magicpoints>0</magicpoints>
				<skillpoints>0</skillpoints>
				<experience>17</experience>
				<spell/>
			</level>
			<level id="3">
				<strength>11</strength>
				<agility>8</agility>
				<resilience>7</resilience>
				<wisdom>7</wisdom>
				<hitpoints>28</hitpoints>
				<magicpoints>5</magicpoints>
				<skillpoints>0</skillpoints>
				<experience>44</experience>
				<spell>Heal</spell>
			</level>
			<level id="4">
				<strength>12</strength>
				<agility>9</agility>
				<resilience>7</resilience>
				<wisdom>8</wisdom>
				<hitpoints>30</hitpoints>
				<magicpoints>9</magicpoints>
				<skillpoints>2</skillpoints>
				<experience>93</experience>
				<spell>Squelch</spell>
			</level>
			<level id="5">
				<strength>13</strength>
				<agility>10</agility>
				<resilience>8</resilience>
				<wisdom>10</wisdom>
				<hitpoints>34</hitpoints>
				<magicpoints>14</magicpoints>
				<skillpoints>4</skillpoints>
				<experience>180</experience>
				<spell/>
			</level>
			<level id="6">
				<strength>15</strength>
				<agility>11</agility>
				<resilience>8</resilience>
				<wisdom>12</wisdom>
				<hitpoints>37</hitpoints>
				<magicpoints>19</magicpoints>
				<skillpoints>7</skillpoints>
				<experience>310</experience>
				<spell>Evac</spell>
			</level>
			<level id="7">
				<strength>17</strength>
				<agility>13</agility>
				<resilience>9</resilience>
				<wisdom>14</wisdom>
				<hitpoints>42</hitpoints>
				<magicpoints>23</magicpoints>
				<skillpoints>9</skillpoints>
				<experience>505</experience>
				<spell/>
			</level>
			<level id="8">
				<strength>19</strength>
				<agility>14</agility>
				<resilience>9</resilience>
				<wisdom>16</wisdom>
				<hitpoints>45</hitpoints>
				<magicpoints>26</magicpoints>
				<skillpoints>12</skillpoints>
				<experience>797</experience>
				<spell/>
			</level>
			<level id="9">
				<strength>22</strength>
				<agility>16</agility>
				<resilience>10</resilience>
				<wisdom>18</wisdom>
				<hitpoints>52</hitpoints>
				<magicpoints>29</magicpoints>
				<skillpoints>14</skillpoints>
				<experience>1235</experience>
				<spell/>
			</level>
			<level id="10">
				<strength>25</strength>
				<agility>18</agility>
				<resilience>11</resilience>
				<wisdom>21</wisdom>
				<hitpoints>59</hitpoints>
				<magicpoints>32</magicpoints>
				<skillpoints>17</skillpoints>
				<experience>1892</experience>
				<spell/>
			</level>
			<level id="11">
				<strength>27</strength>
				<agility>21</agility>
				<resilience>12</resilience>
				<wisdom>24</wisdom>
				<hitpoints>71</hitpoints>
				<magicpoints>34</magicpoints>
				<skillpoints>20</skillpoints>
				<experience>2795</experience>
				<spell> Sizz</spell>
			</level>
			<level id="12">
				<strength>30</strength>
				<agility>24</agility>
				<resilience>13</resilience>
				<wisdom>26</wisdom>
				<hitpoints>80</hitpoints>
				<magicpoints>36</magicpoints>
				<skillpoints>23</skillpoints>
				<experience>4036</experience>
				<spell/>
			</level>
			<level id="13">
				<strength>33</strength>
				<agility>28</agility>
				<resilience>15</resilience>
				<wisdom>28</wisdom>
				<hitpoints>90</hitpoints>
				<magicpoints>38</magicpoints>
				<skillpoints>27</skillpoints>
				<experience>5742</experience>
				<spell/>
			</level>
			<level id="14">
				<strength>36</strength>
				<agility>31</agility>
				<resilience>16</resilience>
				<wisdom>30</wisdom>
				<hitpoints>98</hitpoints>
				<magicpoints>42</magicpoints>
				<skillpoints>32</skillpoints>
				<experience>8087</experience>
				<spell/>
			</level>
			<level id="15">
				<strength>39</strength>
				<agility>35</agility>
				<resilience>18</resilience>
				<wisdom>32</wisdom>
				<hitpoints>109</hitpoints>
				<magicpoints>44</magicpoints>
				<skillpoints>38</skillpoints>
				<experience>11311</experience>
				<spell/>
			</level>
			<level id="16">
				<strength>42</strength>
				<agility>38</agility>
				<resilience>19</resilience>
				<wisdom>35</wisdom>
				<hitpoints>120</hitpoints>
				<magicpoints>48</magicpoints>
				<skillpoints>44</skillpoints>
				<experience>14938</experience>
				<spell/>
			</level>
			<level id="17">
				<strength>45</strength>
				<agility>41</agility>
				<resilience>20</resilience>
				<wisdom>38</wisdom>
				<hitpoints>129</hitpoints>
				<magicpoints>52</magicpoints>
				<skillpoints>49</skillpoints>
				<experience>19018</experience>
				<spell/>
			</level>
			<level id="18">
				<strength>48</strength>
				<agility>45</agility>
				<resilience>22</resilience>
				<wisdom>41</wisdom>
				<hitpoints>140</hitpoints>
				<magicpoints>56</magicpoints>
				<skillpoints>54</skillpoints>
				<experience>23608</experience>
				<spell> Midheal</spell>
			</level>
			<level id="19">
				<strength>51</strength>
				<agility>48</agility>
				<resilience>23</resilience>
				<wisdom>43</wisdom>
				<hitpoints>153</hitpoints>
				<magicpoints>60</magicpoints>
				<skillpoints>59</skillpoints>
				<experience>28771</experience>
				<spell/>
			</level>
			<level id="20">
				<strength>54</strength>
				<agility>52</agility>
				<resilience>25</resilience>
				<wisdom>45</wisdom>
				<hitpoints>166</hitpoints>
				<magicpoints>63</magicpoints>
				<skillpoints>63</skillpoints>
				<experience>34579</experience>
				<spell> Sizzle</spell>
			</level>
			<level id="21">
				<strength>57</strength>
				<agility>54</agility>
				<resilience>26</resilience>
				<wisdom>49</wisdom>
				<hitpoints>179</hitpoints>
				<magicpoints>66</magicpoints>
				<skillpoints>68</skillpoints>
				<experience>41113</experience>
				<spell/>
			</level>
			<level id="22">
				<strength>62</strength>
				<agility>57</agility>
				<resilience>28</resilience>
				<wisdom>53</wisdom>
				<hitpoints>194</hitpoints>
				<magicpoints>68</magicpoints>
				<skillpoints>74</skillpoints>
				<experience>48463</experience>
				<spell/>
			</level>
			<level id="23">
				<strength>66</strength>
				<agility>60</agility>
				<resilience>29</resilience>
				<wisdom>57</wisdom>
				<hitpoints>210</hitpoints>
				<magicpoints>72</magicpoints>
				<skillpoints>80</skillpoints>
				<experience>56731</experience>
				<spell/>
			</level>
			<level id="24">
				<strength>71</strength>
				<agility>63</agility>
				<resilience>31</resilience>
				<wisdom>62</wisdom>
				<hitpoints>224</hitpoints>
				<magicpoints>75</magicpoints>
				<skillpoints>85</skillpoints>
				<experience>66032</experience>
				<spell/>
			</level>
			<level id="25">
				<strength>74</strength>
				<agility>65</agility>
				<resilience>32</resilience>
				<wisdom>68</wisdom>
				<hitpoints>237</hitpoints>
				<magicpoints>81</magicpoints>
				<skillpoints>90</skillpoints>
				<experience>76495</experience>
				<spell/>
			</level>
			<level id="26">
				<strength>79</strength>
				<agility>67</agility>
				<resilience>34</resilience>
				<wisdom>74</wisdom>
				<hitpoints>251</hitpoints>
				<magicpoints>87</magicpoints>
				<skillpoints>95</skillpoints>
				<experience>88265</experience>
				<spell/>
			</level>
			<level id="27">
				<strength>83</strength>
				<agility>69</agility>
				<resilience>35</resilience>
				<wisdom>80</wisdom>
				<hitpoints>264</hitpoints>
				<magicpoints>91</magicpoints>
				<skillpoints>100</skillpoints>
				<experience>101506</experience>
				<spell> Fullheal</spell>
			</level>
			<level id="28">
				<strength>88</strength>
				<agility>71</agility>
				<resilience>37</resilience>
				<wisdom>87</wisdom>
				<hitpoints>278</hitpoints>
				<magicpoints>96</magicpoints>
				<skillpoints>106</skillpoints>
				<experience>116402</experience>
				<spell/>
			</level>
			<level id="29">
				<strength>92</strength>
				<agility>73</agility>
				<resilience>38</resilience>
				<wisdom>94</wisdom>
				<hitpoints>290</hitpoints>
				<magicpoints>102</magicpoints>
				<skillpoints>112</skillpoints>
				<experience>133160</experience>
				<spell> Zing</spell>
			</level>
			<level id="30">
				<strength>96</strength>
				<agility>75</agility>
				<resilience>40</resilience>
				<wisdom>102</wisdom>
				<hitpoints>307</hitpoints>
				<magicpoints>110</magicpoints>
				<skillpoints>117</skillpoints>
				<experience>152012</experience>
				<spell/>
			</level>
			<level id="31">
				<strength>99</strength>
				<agility>78</agility>
				<resilience>41</resilience>
				<wisdom>110</wisdom>
				<hitpoints>320</hitpoints>
				<magicpoints>120</magicpoints>
				<skillpoints>122</skillpoints>
				<experience>173220</experience>
				<spell/>
			</level>
			<level id="32">
				<strength>102</strength>
				<agility>81</agility>
				<resilience>43</resilience>
				<wisdom>118</wisdom>
				<hitpoints>332</hitpoints>
				<magicpoints>130</magicpoints>
				<skillpoints>128</skillpoints>
				<experience>197079</experience>
				<spell> Kasizzle</spell>
			</level>
			<level id="33">
				<strength>105</strength>
				<agility>84</agility>
				<resilience>45</resilience>
				<wisdom>125</wisdom>
				<hitpoints>342</hitpoints>
				<magicpoints>141</magicpoints>
				<skillpoints>135</skillpoints>
				<experience>223920</experience>
				<spell/>
			</level>
			<level id="34">
				<strength>108</strength>
				<agility>87</agility>
				<resilience>46</resilience>
				<wisdom>132</wisdom>
