=== JamesSkemp/media.jamesrskemp/xsd/iTunesPlaylistsToXml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="playlist">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="information">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="updated" type="xs:dateTime"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="track" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all minOccurs="0">
							<xs:element name="name" minOccurs="0" type="xs:string"/>
							<xs:element name="artist" minOccurs="0" type="xs:string"/>
							<xs:element name="rating" minOccurs="0" type="xs:nonNegativeInteger"/>
							<xs:element name="playCount" minOccurs="0" type="xs:nonNegativeInteger"/>
							<xs:element name="lastPlayed" minOccurs="0" type="xs:dateTime"/>
							<xs:element name="album" minOccurs="0" type="xs:string"/>
							<xs:element name="compilation" minOccurs="0" type="xs:boolean"/>
							<xs:element name="trackNumber" minOccurs="0"/>
							<xs:element name="trackCount" minOccurs="0"/>
							<xs:element name="discNumber" minOccurs="0"/>
							<xs:element name="discCount" minOccurs="0"/>
							<xs:element name="year" minOccurs="0"/>
							<xs:element name="genre" minOccurs="0" type="xs:string"/>
							<xs:element name="dateAdded" minOccurs="0" type="xs:dateTime"/>
						</xs:all>
						<xs:attribute name="time"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="time"/>
			<xs:attribute name="tracks" type="xs:nonNegativeInteger"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/media.jamesrskemp/xml/samples/iTunesPlaylistsToXml_Example_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/iTunesPlaylists2Xml.xslt"?><!-- Visit http://jamesrskemp.com/apps/iTunesPlaylists2Xml/?xslt for sample transformations and more. -->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://media.jamesrskemp.com/xsd/iTunesPlaylistsToXml.xsd" name="Example Playlist" time="36:26:15" tracks="464">
<information>
<name>James Skemp</name>
<updated>2009-09-07T09:43:52</updated>
</information>
<!-- Listing of tracks. -->
<track time="4:28"><name>Mary Queen Of Arkansas</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T08:25:43</lastPlayed><album>Tracks</album><trackNumber>1</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:42:35</dateAdded></track>
<track time="2:55"><name>It&apos;s Hard To Be A Saint In The City</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T08:28:38</lastPlayed><album>Tracks</album><trackNumber>2</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:43:13</dateAdded></track>
<track time="2:40"><name>Growin&apos; Up</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T08:31:19</lastPlayed><album>Tracks</album><trackNumber>3</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:43:43</dateAdded></track>
<track time="2:03"><name>Does This Bus Stop At 82nd Street?</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T08:33:23</lastPlayed><album>Tracks</album><trackNumber>4</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:44:07</dateAdded></track>
<track time="4:21"><name>Bishop Danced</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T08:38:12</lastPlayed><album>Tracks</album><trackNumber>5</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:44:27</dateAdded></track>
<track time="4:37"><name>Santa Ana</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T08:42:49</lastPlayed><album>Tracks</album><trackNumber>6</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:45:11</dateAdded></track>
<track time="3:34"><name>Seaside Bar Song</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T08:46:23</lastPlayed><album>Tracks</album><trackNumber>7</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:46:13</dateAdded></track>
<track time="5:57"><name>Zero And Blind Terry</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T08:52:21</lastPlayed><album>Tracks</album><trackNumber>8</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:46:42</dateAdded></track>
<track time="4:27"><name>Linda Let Me Be The One</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T08:58:13</lastPlayed><album>Tracks</album><trackNumber>9</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:47:28</dateAdded></track>
<track time="8:28"><name>Thundercrack</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:06:41</lastPlayed><album>Tracks</album><trackNumber>10</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:48:02</dateAdded></track>
<track time="2:51"><name>Rendezvous</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:09:33</lastPlayed><album>Tracks</album><trackNumber>11</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:49:16</dateAdded></track>
<track time="3:55"><name>Give The Girl A Kiss</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:13:28</lastPlayed><album>Tracks</album><trackNumber>12</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:49:39</dateAdded></track>
<track time="3:18"><name>Iceman</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:16:46</lastPlayed><album>Tracks</album><trackNumber>13</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:50:20</dateAdded></track>
<track time="2:40"><name>Bring On The Night</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:19:26</lastPlayed><album>Tracks</album><trackNumber>14</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:50:46</dateAdded></track>
<track time="3:49"><name>So Young And In Love</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:23:15</lastPlayed><album>Tracks</album><trackNumber>15</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:51:06</dateAdded></track>
<track time="4:31"><name>Hearts Of Stone</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:27:47</lastPlayed><album>Tracks</album><trackNumber>16</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:51:35</dateAdded></track>
<track time="3:00"><name>Don&apos;t Look Back</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:30:47</lastPlayed><album>Tracks</album><trackNumber>17</trackNumber><trackCount>17</trackCount><discNumber>1</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:52:13</dateAdded></track>
<track time="3:47"><name>Restless Nights</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:34:34</lastPlayed><album>Tracks</album><trackNumber>1</trackNumber><trackCount>17</trackCount><discNumber>2</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:53:35</dateAdded></track>
<track time="3:17"><name>A Good Man Is Hard To Find (Pittsburgh)</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:37:52</lastPlayed><album>Tracks</album><trackNumber>2</trackNumber><trackCount>17</trackCount><discNumber>2</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:54:08</dateAdded></track>
<track time="3:55"><name>Roulette</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:41:47</lastPlayed><album>Tracks</album><trackNumber>3</trackNumber><trackCount>17</trackCount><discNumber>2</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:54:34</dateAdded></track>
<track time="3:34"><name>Dollhouse</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:45:21</lastPlayed><album>Tracks</album><trackNumber>4</trackNumber><trackCount>17</trackCount><discNumber>2</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:55:06</dateAdded></track>
<track time="3:46"><name>Where The Bands Are</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:49:07</lastPlayed><album>Tracks</album><trackNumber>5</trackNumber><trackCount>17</trackCount><discNumber>2</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:55:33</dateAdded></track>
<track time="4:03"><name>Loose Ends</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:53:11</lastPlayed><album>Tracks</album><trackNumber>6</trackNumber><trackCount>17</trackCount><discNumber>2</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:56:02</dateAdded></track>
<track time="4:19"><name>Living On The Edge Of The World</name><artist>Bruce Springsteen</artist><rating>0</rating><playCount>1</playCount><lastPlayed>2008-07-31T09:57:30</lastPlayed><album>Tracks</album><trackNumber>7</trackNumber><trackCount>17</trackCount><discNumber>2</discNumber><discCount>4</discCount><year>1998</year><genre>Rock</genre><dateAdded>2008-04-19T12:56:43</dateAdded></track>
