=== JamesSkemp/media.jamesrskemp/xsd/MyCDs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="albums">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="album" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title"/>
							<xs:element name="artist"/>
							<xs:element name="purchase" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" minOccurs="0" type="xs:date"/>
										<xs:element name="place" minOccurs="0"/>
										<xs:element name="price" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="notes" minOccurs="0" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/media.jamesrskemp/xml/MyCDs.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xslt/MyCDs.xslt"?>
<albums xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://media.jamesrskemp.com/xsd/MyCDs.xsd">
	<album id="1">
		<title>Let It Be</title>
		<artist>Beatles, The</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="2">
		<title>One</title>
		<artist>Beatles, The</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="3">
		<title>Yellow Submarine Soundtrack</title>
		<artist>Beatles, The</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="4">
		<title>Best of Blue Öyster Cult Don't Fear the Reaper, The</title>
		<artist>Blue Öyster Cult</artist>
		<purchase>
			<date>2000-08-11</date>
			<price>7.99</price>
		</purchase>
		<notes>Borders</notes>
	</album>
	<album id="5">
		<title>Best of David Bowie 1969/1974, The</title>
		<artist>David Bowie</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="6">
		<title>Songs You Know By Heart: Jimmy Buffett's Greatest Hit(s)</title>
		<artist>Jimmy Buffett</artist>
		<purchase>
			<place>Gift from Mom</place>
			<price>0.00</price>
		</purchase>
		<notes>From Mom pre 12/13/2000. Given back 9/4/2011.</notes>
	</album>
	<album id="7">
		<title>Fiddle Fire: 25 Years of The Charlie Daniels Band</title>
		<artist>Charlie Daniels Band, The</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="8">
		<title>Reptile</title>
		<artist>Eric Clapton</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="9">
		<title>Timepieces The Best of Eric Clapton</title>
		<artist>Eric Clapton</artist>
		<notes>
			Bought before 12/13/2000.
			Sold physical copy for $2 on 3/3/2013 at Mega Media Xchange, 7610 Mineral Point Rd, Madison WI 53719-1689.
		</notes>
	</album>
	<album id="10">
		<title>No Ordinary World</title>
		<artist>Joe Cocker</artist>
		<notes>Bought after 12/13/2000. Sold physical copy for $2 on 2/2/2013 to Mega Media Xchange (7610 Mineral Point Rd, Madison WI).</notes>
	</album>
	<album id="11">
		<title>Cosmo's Factory</title>
		<artist>Creedence Clearwater Revival</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="12">
		<title>Photographs &amp; Memories: His Greatest Hits</title>
		<artist>Jim Croce</artist>
		<notes>Bought before 12/13/2000. Sold to mom for $1 on 9/4/2011.</notes>
	</album>
	<album id="13">
		<title>Very Best of Deep Purple, The</title>
		<artist>Deepest Purple</artist>
		<notes>Bought before 12/13/2000. Sold physical copy for $2 on 2/2/2013 to Mega Media Xchange (7610 Mineral Point Rd, Madison WI).</notes>
	</album>
	<album id="14">
		<title>Sultans of Swing: The Very Best of Dire Straits</title>
		<artist>Dire Straits</artist>
		<notes>After 12/13/2000</notes>
	</album>
	<album id="15">
		<title>Dylan &amp; The Dead</title>
		<artist>Bob Dylan and The Grateful Dead</artist>
		<notes>After 12/13/2000</notes>
	</album>
	<album id="16">
		<title>Blonde on Blonde</title>
		<artist>Bob Dylan</artist>
		<purchase>
			<date>2001-08-30</date>
			<place>Borders (East Madison)</place>
			<price>7.99</price>
		</purchase>
	</album>
	<album id="17">
		<title>Blood on the Tracks</title>
		<artist>Bob Dylan</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="18">
		<title>Essential Bob Dylan, The</title>
		<artist>Bob Dylan</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="19">
		<title>Love And Theft</title>
		<artist>Bob Dylan</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="20">
		<title>Hell Freezes Over</title>
		<artist>Eagles</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="21">
		<title>Greatest Hits</title>
		<artist>Eurythmics</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="22">
		<title>Greatest Hits</title>
		<artist>Fleetwood Mac</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="23">
		<title>Too Legit To Quit</title>
		<artist>Hammer</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="24">
		<title>Janis Joplin's Greatest Hits</title>
		<artist>Janis Joplin</artist>
		<purchase>
			<date>2000-08-11</date>
			<place>Borders</place>
			<price>7.99</price>
		</purchase>
	</album>
	<album id="25">
		<title>Best of Kansas, The</title>
		<artist>Kansas</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="26">
		<title>Gord's Gold Volume II</title>
		<artist>Gordon Lightfoot</artist>
		<purchase>
			<place>Borders</place>
			<price>0.00</price>
		</purchase>
		<notes>Sold physical copy for $2 on 2/2/2013 to Mega Media Xchange (7610 Mineral Point Rd, Madison WI).</notes>
	</album>
	<album id="27">
		<title>Best of the Mamas and the Papas, The</title>
		<artist>Mamas and The Papas, The</artist>
		<notes>20th Century Masters</notes>
	</album>
	<album id="28">
		<title>Satisfy My Soul</title>
		<artist>Bob Marley</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="29">
		<title>Soul Rebel</title>
		<artist>Bob Marley</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="30">
		<title>American Pie</title>
		<artist>Don McLean</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="31">
		<title>Greatest Hits</title>
		<artist>Monkees, The</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="32">
		<title>Best of The Moody Blues, The</title>
		<artist>Moody Blues, The</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="33">
		<title>Complete Hits Collection: 1973-1997, The</title>
		<artist>Billy Joel</artist>
		<notes>CD 1: Greatest Hits Volume I (1973-1977) CD 2: Greatest Hits Volume II (1978-1985) CD
			3: Greatest Hits Volume III (1986-1997) CD 4: "An Evening Of Questions &amp;
			Answers.. &amp; A Little Magic"</notes>
	</album>
	<album id="34">
		<title>Trouble in Shangri-La</title>
		<artist>Stevie Nicks</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="35">
		<title>Greatest Hits</title>
		<artist>Nitty Gritty Dirt Band</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="36">
		<title>Echoes: The Best of Pink Floyd</title>
		<artist>Pink Floyd</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="37">
		<title>Wall, The</title>
		<artist>Pink Floyd</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="38">
		<title>Classic Queen</title>
		<artist>Queen</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="39">
		<title>Greatest Hits</title>
		<artist>Queen</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="40">
		<title>Supernatural</title>
		<artist>Santana</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="41">
		<title>Chants of India</title>
		<artist>Ravi Shankar</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="42">
		<title>You're the One</title>
		<artist>Paul Simon</artist>
		<notes>
			Bought after 12/13/2000.
			Sold physical copy for $2 on 3/3/2013 at Mega Media Xchange, 7610 Mineral Point Rd, Madison WI 53719-1689.
		</notes>
	</album>
	<album id="43">
		<title>Simon and Garfunkel's Greatest Hits</title>
		<artist>Simon and Garfunkel</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="44">
		<title>18 Tracks</title>
		<artist>Bruce Springsteen</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="45">
		<title>Born in the U.S.A.</title>
		<artist>Bruce Springsteen</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="46">
		<title>Bruce Springsteen &amp; The E Street Band Live/1975-85</title>
		<artist>Bruce Springsteen</artist>
		<notes>Bought before 12/13/2000</notes>
	</album>
	<album id="47">
		<title>Bruce Springsteen &amp; The E Street Band Live in New York City</title>
		<artist>Bruce Springsteen</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="48">
		<title>Greetings from Asbury Park N.J.</title>
		<artist>Bruce Springsteen</artist>
		<purchase>
			<date>2000-08-11</date>
			<place>Borders</place>
			<price>7.99</price>
		</purchase>
	</album>
	<album id="49">
		<title>Lucky Town</title>
		<artist>Bruce Springsteen</artist>
		<purchase>
			<place>Gift from Mom</place>
			<price>0.00</price>
		</purchase>
		<notes>Gift from Mom pre 12/13/2000</notes>
	</album>
	<album id="50">
		<title>Nebraska</title>
		<artist>Bruce Springsteen</artist>
		<notes>After 12/13/2000</notes>
	</album>
	<album id="51">
		<title>Wild, The Innocent &amp; The E Street Shuffle, The</title>
		<artist>Bruce Springsteen</artist>
		<purchase>
			<date>2001-08-30</date>
			<place>Barnes &amp; Nobles Bookseller, 7433 Mineral Point Road, Madison WI 53717</place>
			<price>9.99</price>
		</purchase>
		<notes></notes>
	</album>
	<album id="52">
		<title>Best of Steppenwolf, The</title>
		<artist>Steppenwolf</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="53">
		<title>Downtown Train</title>
		<artist>Rod Stewart</artist>
		<notes>Given to me by mom, from her collection.</notes>
	</album>
	<album id="54">
		<title>Ballad Album, The</title>
		<artist>Rod Stewart</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="55">
		<title>Rock Album, The</title>
		<artist>Rod Stewart</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="56">
		<title>Greatest Hits</title>
		<artist>James Taylor</artist>
		<notes>
			Bought before 12/13/2000.
			Sold physical copy for $2 on 3/3/2013 at Mega Media Xchange, 7610 Mineral Point Rd, Madison WI 53719-1689.
		</notes>
	</album>
	<album id="57">
		<title>Best of Three Dog Night, The</title>
		<artist>Three Dog Night</artist>
		<notes>Bought after 12/13/2000</notes>
	</album>
	<album id="58">
		<title>Original Masters</title>
		<artist>Jethro Tull</artist>
		<notes>Bought after 12/13/2000</notes>
