=== JamesSkemp/media.jamesrskemp/xsd/ResonanceOfFate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ResonanceOfFate">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Arena">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Ranks">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Rank" maxOccurs="50">
											<xs:complexType>
												<xs:sequence>
												<xs:element name="Enemies">
												<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="unbounded" name="Enemy">
												<xs:complexType>
												<xs:attribute name="name" use="required"/>
												<xs:attribute name="quantity"
												type="xs:positiveInteger" use="optional"/>
												<xs:attribute name="level"
												type="xs:positiveInteger"/>
												</xs:complexType>
												</xs:element>
												</xs:sequence>
												</xs:complexType>
												</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:positiveInteger"
												use="required"/>
												<xs:attribute name="chapter"/>
												<xs:attribute name="price"/>
												<xs:attribute name="battleCoins"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Multipliers">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="Multiplier">
											<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger"
												use="required"/>
												<xs:attribute name="value" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Characters">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="3" minOccurs="3" name="Character">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Levels">
											<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="unbounded" name="Level">
												<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger"
												use="required"/>
												<xs:attribute name="hitPoints"
												type="xs:positiveInteger" use="required"/>
												<xs:attribute name="weight"
												type="xs:positiveInteger" use="required"/>
												</xs:complexType>
												</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Skills">
											<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="unbounded" name="Skill">
												<xs:complexType>
												<xs:attribute name="type" use="required"/>
												<xs:attribute name="level"
												type="xs:positiveInteger" use="required"/>
												<xs:attribute name="name" use="required"/>
												</xs:complexType>
												</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Weapons">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Listing">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="Weapon">
											<xs:complexType>
												<xs:attribute name="name" use="required"/>
												<xs:attribute name="type" use="required"/>
												<xs:attribute name="attained" use="required"/>
												<xs:attribute name="description" use="required"/>
												<xs:attribute name="attackPower"/>
												<xs:attribute name="gaugeBreak"/>
												<xs:attribute name="knockback"/>
												<xs:attribute name="chargeSpeed"/>
												<xs:attribute name="chargeAcceleration"/>
												<xs:attribute name="rapidFire"/>
												<xs:attribute name="spread"/>
												<xs:attribute name="magazineSize"/>
												<xs:attribute name="weight" use="required"/>
												<xs:attribute name="imageLocation"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Leveling">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="Level">
											<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger"
												use="required"/>
												<xs:attribute name="experience"
												type="xs:nonNegativeInteger" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="CustomParts">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="Parts">
											<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="unbounded" minOccurs="0"
												name="purchase">
												<xs:complexType>
												<xs:simpleContent>
												<xs:extension base="xs:string">
												<xs:attribute name="cost"/>
												</xs:extension>
												</xs:simpleContent>
												</xs:complexType>
												</xs:element>
												<xs:element maxOccurs="1" minOccurs="0"
												name="tinker">
												<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="unbounded" name="material">
												<xs:complexType>
												<xs:attribute name="name" use="required"/>
												<xs:attribute name="quantity"/>
												</xs:complexType>
												</xs:element>
												<xs:element maxOccurs="unbounded" name="location"
												/>
												</xs:sequence>
												<xs:attribute name="cost"/>
												</xs:complexType>
												</xs:element>
												<xs:element maxOccurs="unbounded" minOccurs="0"
												name="reward"/>
												</xs:sequence>
												<xs:attribute name="name" use="required"/>
												<xs:attribute name="imageLocation"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Missions">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="1" name="Mission">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Client">
											<xs:complexType>
												<xs:attribute name="name"/>
												<xs:attribute name="location"/>
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="1" name="Rewards">
											<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="unbounded" minOccurs="0"
												name="Item">
												<xs:complexType>
												<xs:attribute name="name" use="required"/>
												<xs:attribute name="quantity"/>
												</xs:complexType>
												</xs:element>
												</xs:sequence>
												<xs:attribute name="hunterPoints"/>
												<xs:attribute name="rubies"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="Description"/>
										<xs:element name="Notes"/>
									</xs:sequence>
									<xs:attribute name="chapter" use="required"/>
									<xs:attribute name="title" use="required"/>
									<xs:attribute name="type" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Enemies">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Special">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="Challenge">
											<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="unbounded" name="Enemy">
												<xs:complexType>
												<xs:attribute name="name" use="required"/>
												<xs:attribute name="quantity"/>
												<xs:attribute name="level"
												type="xs:positiveInteger" use="required"/>
												<xs:attribute name="leader" type="xs:boolean"/>
												</xs:complexType>
												</xs:element>
												<xs:element name="Reward">
												<xs:complexType>
												<xs:attribute name="name" use="required"/>
												</xs:complexType>
												</xs:element>
												<xs:element minOccurs="0" name="Notes"/>
												</xs:sequence>
												<xs:attribute name="chapter"
												type="xs:positiveInteger" use="required"/>
												<xs:attribute name="level" type="xs:positiveInteger"
												use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/media.jamesrskemp/xml/ResonanceOfFate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Licensed under the Creative Commons License Attribution-Noncommercial-Share Alike 3.0 (http://creativecommons.org/licenses/by-nc-sa/3.0/). Contact information for attribution at http://jamesrskemp.com/ -->
<?xml-stylesheet type="text/xsl" href="../xslt/ResonanceOfFate.xsl"?>
<ResonanceOfFate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://media.jamesrskemp.com/xsd/ResonanceOfFate.xsd">
	<!-- Last updated: 2/18/2011 at 8:08 PM Central Time -->
	<Arena>
		<Ranks>
			<Rank id="1" chapter="1" price="300" battleCoins="1 Bronze"><Enemies><Enemy name="Brownie" level="6"/><Enemy name="Cheap Gunner" quantity="2" level="6"/></Enemies></Rank>
			<Rank id="2" chapter="2" price="600" battleCoins="2 Bronze"><Enemies><Enemy name="Cheap Gunner" quantity="2" level="5"/><Enemy name="Cheap Gunner Machinegun" level="6"/></Enemies></Rank>
			<Rank id="3" chapter="2" price="900" battleCoins="3 Bronze"><Enemies><Enemy name="Oil Brownie" quantity="3" level="7"/></Enemies></Rank>
			<Rank id="4" chapter="2" price="1200" battleCoins="4 Bronze"><Enemies><Enemy name="Liese Gunner Magnum" quantity="2" level="12"/><Enemy name="Drum Pixie" quantity="2" level="6"/><Enemy name="Green Gear" level="17"/></Enemies></Rank>
			<Rank id="5" chapter="2" price="1500" battleCoins="5 Bronze"><Enemies><Enemy name="Liese Gunner Magnum" quantity="2" level="11"/><Enemy name="Oil Brownie" quantity="2" level="6"/><Enemy name="Green Gear" level="16"/></Enemies></Rank>
			<Rank id="6" chapter="3" price="1800" battleCoins="7 Bronze"><Enemies><Enemy name="Hound" quantity="2" level="8"/><Enemy name="Yellow Gear" quantity="2" level="18"/></Enemies></Rank>
			<Rank id="7" chapter="3" price="2100" battleCoins="9 Bronze"><Enemies><Enemy name="Hound" quantity="2" level="8"/><Enemy name="Drum Hobbit" level="9"/><Enemy name="Light Gunner MG" quantity="2" level="11"/></Enemies></Rank>
			<Rank id="8" chapter="4" price="2400" battleCoins="10 Bronze"><Enemies><Enemy name="Coppélia Gunhead" quantity="2" level="14"/><Enemy name="Coppélia Chainsaw" quantity="2" level="13"/></Enemies></Rank>
			<Rank id="9" chapter="4" price="2700" battleCoins="11 Bronze"><Enemies><Enemy name="Coppélia Flamer" quantity="5" level="14"/></Enemies></Rank>
			<Rank id="10" chapter="5" price="3000" battleCoins="12 Bronze"><Enemies><Enemy name="Marionette Bazooka" quantity="3" level="15"/></Enemies></Rank>
			<Rank id="11" chapter="5" price="3300" battleCoins="13 Bronze"><Enemies><Enemy name="Marionette Chainsaw" quantity="4" level="20"/></Enemies></Rank>
			<Rank id="12" chapter="6" price="3600" battleCoins="14 Bronze"><Enemies><Enemy name="Middle Gunner Magnum" quantity="2" level="23"/><Enemy name="Drum Troll" quantity="2" level="24"/></Enemies></Rank>
			<Rank id="13" chapter="6" price="3900" battleCoins="18 Bronze"><Enemies><Enemy name="Jumbo Pixie" quantity="2" level="51"/><Enemy name="Drum Troll" quantity="2" level="24"/></Enemies></Rank>
			<Rank id="14" chapter="6" price="4200" battleCoins="22 Bronze"><Enemies><Enemy name="Fenrir" quantity="3" level="24"/><Enemy name="Middle Gunner Magnum" quantity="2" level="23"/></Enemies></Rank>
			<Rank id="15" chapter="6" price="4500" battleCoins="26 Bronze"><Enemies><Enemy name="Snow Brownie" quantity="5" level="23"/></Enemies></Rank><!-- first battle level 22 (?) -->
			<Rank id="16" chapter="6" price="4800" battleCoins="28 Bronze"><Enemies><Enemy name="Fenrir" quantity="2" level="24"/><Enemy name="Snow Brownie" quantity="3" level="22"/></Enemies></Rank>
			<Rank id="17" chapter="6" price="5100" battleCoins="30 Bronze"><Enemies><Enemy name="Snow Brownie" level="22"/><Enemy name="Middle Gunner Magnum" quantity="2" level="23"/><Enemy name="Middle Gunner Machinegun" level="23"/></Enemies></Rank>
			<Rank id="18" chapter="6" price="5400" battleCoins="34 Bronze"><Enemies><Enemy name="Humbaba" quantity="2" level="47"/><Enemy name="Middle Gunner Magnum" level="25"/><Enemy name="Middle Gunner Machinegun" level="25"/></Enemies></Rank>
			<Rank id="19" chapter="6" price="5700" battleCoins="38 Bronze"><Enemies><Enemy name="Bigfoot" level="63"/></Enemies></Rank><!-- first battle level 55 (?) -->
			<Rank id="20" chapter="6" price="6000" battleCoins="40 Bronze"><Enemies><Enemy name="Black Dog" quantity="2" level="26"/></Enemies></Rank>
			<Rank id="21" chapter="6" price="6300" battleCoins="1 Silver"><Enemies><Enemy name="Middle Gunner Shotgun" level="23"/><Enemy name="Middle Gunner Machinegun" quantity="2" level="23"/><Enemy name="Black Dog" quantity="2" level="24"/></Enemies></Rank>
			<Rank id="22" chapter="6" price="6600" battleCoins="2 Silver"><Enemies><Enemy name="Humbaba II" quantity="2" level="34"/></Enemies></Rank>
			<Rank id="23" chapter="6" price="6900" battleCoins="3 Silver"><Enemies><Enemy name="Humbaba II" quantity="2" level="34"/><Enemy name="Middle Gunner Magnum" quantity="2" level="23"/></Enemies></Rank>
			<Rank id="24" chapter="8" price="7200" battleCoins="4 Silver"><Enemies><Enemy name="Handgun Hermit" quantity="5" level="28"/></Enemies></Rank><!-- Possibly 27s at 71 - 73 - 74 (next battle at 71-73-75) -->
			<Rank id="25" chapter="8" price="7500" battleCoins="5 Silver"><Enemies><Enemy name="Drum Spriggan" quantity="3" level="29"/><Enemy name="Hellhound" quantity="2" level="30"/></Enemies></Rank>
			<Rank id="26" chapter="8" price="7800" battleCoins="7 Silver"><Enemies><Enemy name="Hellhound" quantity="5" level="30"/></Enemies></Rank>
			<Rank id="27" chapter="8" price="8100" battleCoins="9 Silver"><Enemies><Enemy name="Torch Brownie" quantity="2" level="27"/><Enemy name="Drum Spriggan" quantity="2" level="29"/></Enemies></Rank>
			<Rank id="28" chapter="8" price="8400" battleCoins="10 Silver"><Enemies><Enemy name="Handgun Hermit" quantity="2" level="28"/><Enemy name="Torch Brownie" quantity="2" level="28"/></Enemies></Rank><!-- first battle, all level 27 -->
			<Rank id="29" chapter="8" price="8700" battleCoins="11 Silver"><Enemies><Enemy name="Torch Brownie" quantity="2" level="27"/><Enemy name="Drum Spriggan" quantity="2" level="29"/><Enemy name="Jumbo Troll" level="62"/></Enemies></Rank>
			<Rank id="30" chapter="8" price="9000" battleCoins="12 Silver"><Enemies><Enemy name="Soldier GL-MG" quantity="2" level="28"/><Enemy name="Hellhound" quantity="2" level="30"/></Enemies></Rank>
			<Rank id="31" chapter="8" price="9300" battleCoins="13 Silver"><Enemies><Enemy name="Shell Tank" level="52"/><Enemy name="Soldier GL-SO" level="28"/><Enemy name="Soldier GL-AR" quantity="2" level="28"/></Enemies></Rank>
			<Rank id="32" chapter="8" price="9600" battleCoins="14 Silver"><Enemies><Enemy name="Ifreet" level="82"/><Enemy name="Torch Brownie" quantity="2" level="27"/></Enemies></Rank>
			<Rank id="33" chapter="8" price="9900" battleCoins="18 Silver"><Enemies><Enemy name="Red Gear" level="76"/><Enemy name="Gang King" quantity="2" level="55"/></Enemies></Rank>
			<Rank id="34" chapter="8" price="10200" battleCoins="22 Silver"><Enemies><Enemy name="Poison Brownie" quantity="2" level="30"/><Enemy name="Shotgun Hermit" quantity="2" level="27"/></Enemies></Rank>
			<Rank id="35" chapter="8" price="10500" battleCoins="26 Silver"><Enemies><Enemy name="Fáfnir" level="74"/></Enemies></Rank><!-- unknown material g -->
			<Rank id="36" chapter="9" price="10800" battleCoins="28 Silver"><Enemies><Enemy name="Soldier PE-HG" level="28"/><Enemy name="Soldier PE-SG" level="28"/><Enemy name="Soldier PE-SO" level="28"/></Enemies></Rank>
			<Rank id="37" chapter="9" price="11100" battleCoins="30 Silver"><Enemies><Enemy name="Solider PE-SH" level="53"/><Enemy name="Queen Soldier PE-HG" level="28"/><Enemy name="Queen Soldier PE-SM" level="28"/></Enemies></Rank><!-- first battle levels 53, 27, 27 -->
			<Rank id="38" chapter="9" price="11400" battleCoins="34 Silver"><Enemies><Enemy name="Mine Tank" level="79"/><Enemy name="Solider PE-HG" level="29"/><Enemy name="Soldier PE-SG" level="29"/></Enemies></Rank><!-- first battle levels 77, 28, 28 -->
			<Rank id="39" chapter="9" price="11700" battleCoins="38 Silver"><Enemies><Enemy name="Black Gear" level="83"/><Enemy name="Mine Tank" level="79"/><Enemy name="Soldier PE-SH" level="54"/><Enemy name="Queen Soldier PE-SM" level="28"/></Enemies></Rank><!-- first battle levels 81, 77, 53, 27; second battle levels 82, 78, 53, 28 -->
			<Rank id="40" chapter="9" price="12000" battleCoins="40 Silver"><Enemies><Enemy name="Black Gear" level="81"/><Enemy name="Lyrical Hermit" quantity="3" level="42"/></Enemies></Rank>
			<Rank id="41" chapter="10" price="12300" battleCoins="1 Gold"><Enemies><Enemy name="Black Gear" quantity="2" level="83"/><Enemy name="Mist Hermit" quantity="3" level="43"/></Enemies></Rank><!-- first battle levels 81, 42; second battle levels 82, 43 -->
			<Rank id="42" chapter="10" price="12600" battleCoins="2 Gold"><Enemies><Enemy name="Ullikummi" quantity="2" level="69"/></Enemies></Rank><!-- first battle level 60, second battle level 61 -->
			<Rank id="43" chapter="14" price="12900" battleCoins="3 Gold"><Enemies><Enemy name="Soldier RO-SH" level="88"/><Enemy name="Solider RO-HG" quantity="2" level="84"/><Enemy name="Sköll" quantity="2" level="73"/></Enemies></Rank><!-- first battle levels 86, 82, 71; second battle 87, 83, 72 -->
			<Rank id="44" chapter="15" price="13200" battleCoins="4 Gold"><Enemies><Enemy name="Enkidu" level="96"/><Enemy name="Soldier RO-SH" quantity="2" level="86"/><Enemy name="Soldier RO-AR" quantity="2" level="82"/></Enemies></Rank>
			<Rank id="45" chapter="16" price="13500" battleCoins="5 Gold"><Enemies><Enemy name="ST210-G Cannon" quantity="2" level="145"/><Enemy name="ST344-CO1" level="144"/><Enemy name="Soldier RO-SH" level="86"/><Enemy name="Soldier RO-SG" level="82"/></Enemies></Rank><!-- direct kills = leveling HGs is a breeze -->
