=== JamesSkemp/media.jamesrskemp/xsd/2011/01/KingdomHeartsBirthBySleep.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="KingdomHeartsBirthBySleep">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Abilities">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="Ability">
								<xs:complexType>
									<xs:attribute name="Name" use="required"/>
									<xs:attribute name="Type" use="required"/>
									<xs:attribute name="Maximum" type="xs:positiveInteger"
										use="required"/>
									<xs:attribute name="Description" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Characters">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="3" name="Character">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Commands">
											<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="unbounded" name="Command">
												<xs:complexType>
												<xs:attribute name="Id" type="xs:positiveInteger"
												use="required"/>
												<xs:attribute name="Name" use="required"/>
												<xs:attribute name="Type" use="required"/>
												<xs:attribute name="Subtype"/>
												<xs:attribute name="Slots"
												type="xs:positiveInteger"/>
												<xs:attribute name="MaximumLevel"
												type="xs:positiveInteger"/>
												<xs:attribute name="Cost"
												type="xs:positiveInteger"/>
												</xs:complexType>
												</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Melding">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="Meld">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="2" minOccurs="2" name="Ingredient"/>
										<xs:element name="Crystals" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
												<xs:element maxOccurs="7" name="Crystal">
												<xs:complexType>
												<xs:attribute name="Name" use="required"/>
												<xs:attribute name="Ability" use="required"/>
												</xs:complexType>
												</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="0" name="Characters">
											<xs:complexType>
												<xs:attribute name="Terra" type="xs:boolean"/>
												<xs:attribute name="Ven" type="xs:boolean"/>
												<xs:attribute name="Aqua" type="xs:boolean"/>
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="0" name="Notes"/>
									</xs:sequence>
									<xs:attribute name="Id" type="xs:positiveInteger" use="required"/>
									<xs:attribute name="Command" use="required"/>
									<xs:attribute name="Type" use="required"/>
									<xs:attribute name="Rare" type="xs:boolean"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesSkemp/media.jamesrskemp/xml/KingdomHeartsBirthBySleep.xml
<?xml version="1.0" encoding="UTF-8"?>
<KingdomHeartsBirthBySleep xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://media.jamesrskemp.com/xsd/2011/01/KingdomHeartsBirthBySleep.xsd">
	<Abilities>
		<Ability Name="Treasure Magnet" Type="Prizes" Maximum="5" Description="Automatically scoops up nearby prizes for you. Multi-install the ability to increase range."/>
		<Ability Name="HP Prize Plus" Type="Prizes" Maximum="3" Description="Increases the number of HP prizes enemies drop. Multi-install the ability for even more prizes."/>
		<Ability Name="Link Prize Plus" Type="Prizes" Maximum="3" Description="Increases the number of D-Link prizes enemies drop. Multi-install the ability for even more prizes."/>
		<Ability Name="Lucky Strike" Type="Prizes" Maximum="5" Description="Increases the number of prize boxes enemies drop. Multi-install the ability for even more prizes."/>
		<Ability Name="HP Boost" Type="Stats" Maximum="3" Description="Increases your HP. Multi-install the ability to bump it up even further. (Adds 10%, rounded down.)"/>
		<Ability Name="Fire Boost" Type="Stats" Maximum="3" Description="Increases the damage dealt by your Fire commands. Multi-install the ability to deal even more damage."/>
		<Ability Name="Blizzard Boost" Type="Stats" Maximum="3" Description="Increases the damage dealt by your Blizzard commands. Multi-install the ability to deal even more damage."/>
		<Ability Name="Thunder Boost" Type="Stats" Maximum="3" Description="Increases the damage dealt by your Thunder commands. Multi-install the ability to deal even more damage."/>
		<Ability Name="Cure Boost" Type="Stats" Maximum="3" Description="Increases the amount of HP you recover with Cure commands. Multi-install the ability to recover even more."/>
		<Ability Name="Item Boost" Type="Stats" Maximum="3" Description="Increases the effectiveness of recovery item commands. Multi-install the ability for an even larger improvement."/>
		<Ability Name="Attack Haste" Type="Stats" Maximum="5" Description="Shortens the reload time for all attack commands installed in your deck. Multi-install the ability for even quicker reloading."/>
		<Ability Name="Magic Haste" Type="Stats" Maximum="5" Description="Shortens the reload time for all magic commands installed in your deck. Multi-install the ability for even quicker reloading."/>
		<Ability Name="Combo Finish Boost" Type="Stats" Maximum="2" Description="Increases the damage dealt by the last blow of your combos. Multi-install the ability to deal even more damage."/>
		<Ability Name="Finish Boost" Type="Stats" Maximum="2" Description="Increases the damage dealt by your Finish command. Multi-install the ability to deal even more damage."/>
		<Ability Name="Fire Screen" Type="Stats" Maximum="2" Description="Increases your resistance to Fire attacks. Multi-install the ability to bump it up even further. +20% per level."/>
		<Ability Name="Blizzard Screen" Type="Stats" Maximum="2" Description="Increases your resistance to Blizzard attacks (20%). Multi-install the ability to bump it up even further. +20% per level."/>
		<Ability Name="Thunder Screen" Type="Stats" Maximum="2" Description="Increases your resistance to Thunder attacks (20%). Multi-install the ability to bump it up even further. +20% per level."/>
		<Ability Name="Dark Screen" Type="Stats" Maximum="2" Description="Increases your resistance to darkness-based attacks (20%). Multi-install the ability to bump it up even further. +20% per level."/>
		<Ability Name="Reload Boost" Type="Stats" Maximum="1" Description="Shortens the reload time for all commands installed in your deck whenever your HP falls below 25%."/>
		<Ability Name="Defender" Type="Stats" Maximum="1" Description="Increases your Defense whenever your HP falls below 25%."/>
		<Ability Name="Combo Plus" Type="Support" Maximum="3" Description="Adds one stroke to your ground combos. Multi-install the ability for even longer combos."/>
		<Ability Name="Air Combo Plus" Type="Support" Maximum="3" Description="Adds one stroke to your aerial combos. Multi-install the ability for even longer combos."/>
		<Ability Name="Exp Chance" Type="Support" Maximum="1" Description="Doubles the EXP you receive whenever your HP falls below 25%."/>
		<Ability Name="Exp Walker" Type="Support" Maximum="1" Description="Awards you 1 EXP for every step you take."/>
		<Ability Name="Damage Syphon" Type="Support" Maximum="1" Description="Restores some of the Focus Gauge when you take damage."/>
		<Ability Name="Second Chance" Type="Support" Maximum="1" Description="Ensures you always retain 1 HP after an attack that would otherwise finish you off, unless you are already down to 1 HP."/>
		<Ability Name="Once More" Type="Support" Maximum="1" Description="Ensures you always retain 1 HP throughout a combo that would otherwise finish you off, unless you are already at 1 HP when the first attack hits."/>
		<Ability Name="Scan" Type="Support" Maximum="1" Description="Displays the HP of the targeted enemy."/>
		<Ability Name="Leaf Bracer" Type="Support" Maximum="1" Description="Prevents you from taking damage while using Cure commands."/>
	</Abilities>
	<!-- Reports > Command Collection -->
	<Characters>
		<Character Name="Terra">
			<Commands>
				<!-- Terra : 128/195 -->
				<Command Id="1" Name="Quick Blitz" Type="Combat" Subtype="Attacks" Cost="100"/>
				<Command Id="2" Name="Blitz" Type="Combat" Subtype="Attacks" MaximumLevel="4" Cost="1200"/>
				<Command Id="3" Name="Meteor Crash" Type="Combat" Subtype="Attacks" MaximumLevel="5" Slots="2"/>
				<Command Id="4" Name="Sliding Dash" Type="Combat" Subtype="Attacks" MaximumLevel="3" Cost="100"/>
				<Command Id="5" Name="Fire Dash" Type="Combat" Subtype="Attacks" MaximumLevel="4" Cost="150"/>
				<Command Id="6" Name="Dark Haze" Type="Combat" Subtype="Attacks" MaximumLevel="4" Cost="1100"/>
				<Command Id="7" Name="Sonic Blade" Type="Combat" Subtype="Attacks" MaximumLevel="5" Cost="2000"/>
				<!-- 1-8 -->
				<Command Id="9" Name="Zantetsuken" Type="Combat" Subtype="Attacks" MaximumLevel="5" Cost="1700"/>
				<Command Id="10" Name="Strike Raid" Type="Combat" Subtype="Attacks" MaximumLevel="3" Cost="100"/>
				<Command Id="11" Name="Freeze Raid" Type="Combat" Subtype="Attacks" MaximumLevel="4" Cost="200"/>
				<Command Id="12" Name="Fire Surge" Type="Combat" Subtype="Attacks" MaximumLevel="3" Cost="650"/>
				<Command Id="13" Name="Thunder Surge" Type="Combat" Subtype="Attacks" MaximumLevel="4" Cost="700"/>
				<Command Id="14" Name="Aerial Slam" Type="Combat" Subtype="Attacks" MaximumLevel="4" Cost="1500"/>
				<Command Id="15" Name="Ars Solum" Type="Combat" Subtype="Attacks" MaximumLevel="6"/>
				<Command Id="16" Name="Poison Edge" Type="Combat" Subtype="Attacks" MaximumLevel="3" Cost="150"/>
				<Command Id="17" Name="Blizzard Edge" Type="Combat" Subtype="Attacks" MaximumLevel="3" Cost="200"/>
				<Command Id="18" Name="Stun Edge" Type="Combat" Subtype="Attacks" MaximumLevel="3" Cost="150"/>
				<Command Id="19" Name="Slot Edge" Type="Combat" Subtype="Attacks" Cost="700"/>
				<Command Id="20" Name="Fire Strike" Type="Combat" Subtype="Attacks" MaximumLevel="3" Cost="450"/>
				<Command Id="21" Name="Confusion Strike" Type="Combat" Subtype="Attacks" MaximumLevel="3" Cost="450"/>
				<Command Id="22" Name="Binding Strike" Type="Combat" Subtype="Attacks" MaximumLevel="3" Cost="400"/>
				<Command Id="23" Name="Brutal Blast" Type="Combat" Subtype="Attacks" MaximumLevel="4" Cost="1800"/>
				<Command Id="24" Name="Magnet Spiral" Type="Combat" Subtype="Attacks" MaximumLevel="5" Cost="2300"/>
				<Command Id="25" Name="Windcutter" Type="Combat" Subtype="Attacks" MaximumLevel="5" Cost="1500"/>
				<Command Id="26" Name="Limit Storm" Type="Combat" Subtype="Attacks" MaximumLevel="5" Cost="1500"/>
				<Command Id="27" Name="Collision Magnet" Type="Combat" Subtype="Attacks" MaximumLevel="4" Cost="1300"/>
				<Command Id="28" Name="Geo Impact" Type="Combat" Subtype="Attacks" MaximumLevel="5" Slots="2" Cost="2100"/>
				<Command Id="29" Name="Sacrifice" Type="Combat" Subtype="Attacks" MaximumLevel="5" Cost="1500"/>
				<Command Id="30" Name="Break Time" Type="Combat" Subtype="Attacks" MaximumLevel="4"/>
				
				<Command Id="31" Name="Fire" Type="Combat" Subtype="Magic" MaximumLevel="3" Cost="100"/>
				<Command Id="32" Name="Fira" Type="Combat" Subtype="Magic" MaximumLevel="3" Cost="500"/>
				<Command Id="33" Name="Firaga" Type="Combat" Subtype="Magic" Cost="1200"/>
				<Command Id="34" Name="Dark Firaga" Type="Combat" Subtype="Magic" MaximumLevel="5" Cost="2000"/>
				<Command Id="35" Name="Fission Firaga" Type="Combat" Subtype="Magic" Cost="1500"/>
				<Command Id="36" Name="Crawling Fire" Type="Combat" Subtype="Magic" Cost="1800"/>
				<Command Id="37" Name="Blizzard" Type="Combat" Subtype="Magic" MaximumLevel="3" Cost="100"/>
				<Command Id="38" Name="Blizzara" Type="Combat" Subtype="Magic" Cost="500"/>
				<Command Id="39" Name="Blizzaga" Type="Combat" Subtype="Magic" MaximumLevel="4" Cost="1200"/>
				<Command Id="40" Name="Thunder" Type="Combat" Subtype="Magic" Cost="150"/>
				<Command Id="41" Name="Thundara" Type="Combat" Subtype="Magic" Cost="600"/>
				<Command Id="42" Name="Thundaga" Type="Combat" Subtype="Magic" MaximumLevel="4" Cost="1300"/>
				<Command Id="43" Name="Cure" Type="Combat" Subtype="Magic" MaximumLevel="3" Cost="150"/>
				<Command Id="44" Name="Cura" Type="Combat" Subtype="Magic" Cost="600"/>
				<Command Id="45" Name="Curaga" Type="Combat" Subtype="Magic" MaximumLevel="4" Cost="1300"/>
				<Command Id="46" Name="Esuna" Type="Combat" Subtype="Magic" Cost="600"/>
				<Command Id="47" Name="Mine Shield" Type="Combat" Subtype="Magic" MaximumLevel="4"/>
				<Command Id="48" Name="Mine Square" Type="Combat" Subtype="Magic" MaximumLevel="4" Cost="1000"/>
				<Command Id="49" Name="Zero Gravity" Type="Combat" Subtype="Magic" Cost="150"/>
